### ISSUE TITLE
tensorflow.python.framework.errors_impl.DataLossError

### ISSUE THREAD

**Issue by kyotarohorio** [isl-org/Open3D-ML#222]
I got this error when trying to test by using pretrained RandLA-Net
![Screenshot from 2021-02-16 02-09-04](https://user-images.githubusercontent.com/70308688/108032926-8e40df00-7076-11eb-81d5-c743e5fb55ad.png)

**Comment by sanskar107** [comment]
@kyotarohorio  could you post your inference script here?

**Comment by kyotarohorio** [comment]
@sanskar107 sorry, yes. 

`import os
import open3d.ml as _ml3d
import open3d.ml.tf as ml3d

cfg_file = "./ml3d/configs/randlanet_toronto3d.yml"
cfg = _ml3d.utils.Config.load_from_file(cfg_file)

model = ml3d.models.RandLANet(**cfg.model)
cfg.dataset['dataset_path'] = "./data/demo"
dataset = ml3d.datasets.Toronto3D(cfg.dataset.pop('dataset_path', None), **cfg.dataset)
pipeline = ml3d.pipelines.SemanticSegmentation(model, dataset=dataset, device="gpu", **cfg.pipeline)

# download the weights.
ckpt_folder = "./logs/"
os.makedirs(ckpt_folder, exist_ok=True)
ckpt_path = ckpt_folder + "randlanet_toronto3d_202010091250.zip"
randlanet_url = "https://storage.googleapis.com/open3d-releases/model-zoo/randlanet_toronto3d_202010091250.zip"
if not os.path.exists(ckpt_path):
    cmd = "wget {} -O {}".format(randlanet_url, ckpt_path)
    os.system(cmd)

# load the parameters.
pipeline.load_ckpt(ckpt_path=ckpt_path)

test_split = dataset.get_split("test")
data = test_split.get_data(0)

# run inference on a single example.
# returns dict with 'predict_labels' and 'predict_scores'.
result = pipeline.run_inference(data)

# evaluate performance on the test set; this will write logs to './logs'.
pipeline.run_test()`

**Comment by m16m** [comment]
Hello.
I want to predict an pts file, so I use S3DIS pretrained model.
I have the same issue. So I woul'd like to know if anyone resolved it ?
Thank's.

**Comment by hduonggithub** [comment]
@sanskar107 
I think there is some issues with tensorflow for this RandLA-Net model.

I was able to run the similar code from @kyotarohorio for s3dis dataset successfully with torch. But I could not run the code with tensorflow version.

This is another error I got when loading the pretrained model with tensorflow

> Exception has occ_urred: DataLossError
> Unable to open table file ./logs/RandLANet_S3DIS_torch/checkpoint/randlanet_s3dis_202010091238.zip: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
> 
> During handling of the above exception, another exception occurred:
> 
>   File "/mnt/d/Open3D-ML-master/examples/hd_predict_pcd.py", line 37, in <module>
>     pipeline.load_ckpt(ckpt_path=ckpt_path_tf)

**Comment by sanskar107** [comment]
This is a typical problem in tensorflow. Your ckpt path should be `./logs/RandLANet_S3DIS_tf/checkpoint/ckpt-91`, please remove the trailing part.

**Comment by sanskar107** [comment]
@hduonggithub thanks for reporting this, I'll try to reproduce the results and fix them. btw, these warnings are fixed in the lastest `dev` branch, which will be out in next release (within a week).

**Comment by sanskar107** [comment]
@hduonggithub The weight file got corrupted. #288  should fix this issue.
Here is the link for new weights - 
https://storage.googleapis.com/open3d-releases/model-zoo/randlanet_s3dis_202106011448utc.zip

**Comment by hduonggithub** [comment]
Thanks @sanskar107 

I will give it a try!

**Comment by hduonggithub** [comment]
Thanks @sanskar107 

I will give it a try!

**Comment by hduonggithub** [comment]
Hi @sanskar107 

I now have a "out of memory" error with tensorflow. With  the same setting, torch has no problem. Any suggestion? Thanks!

021-06-02 13:48:18.851168: F tensorflow/core/kernels/bias_op_gpu.cu.cc:92] Non-OK-status: GpuLaunchKernel(BiasNHWCKernel<T>, config.block_count, config.thread_per_block, 0, d.stream(), config.virtual_thread_count, input, bias, output, bias_size) status: Internal: out of memory

**Comment by sanskar107** [comment]
https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth

**Comment by hduonggithub** [comment]
Thanks @sanskar107 !

I did try to set a limit usage for GOU down to 1GB, and it works. The result is also comparable to torch's result.

tf.config.experimental.set_virtual_device_configuration(
        gpus[0],
        [tf.config.experimental.VirtualDeviceConfiguration(memory_limit=1024)])

**INFO - 2021-06-03 09:00:27,628 - semantic_segmentation - Overall Accuracy : 0.830
INFO - 2021-06-03 09:00:27,629 - semantic_segmentation - Overall IOU : 0.546**

**Comment by sanskar107** [comment]
@hduonggithub feel free to close the issue if everything is resolved.
