### ISSUE TITLE
How to predict my own point cloud data using pretrained Semantic3d model?

### ISSUE THREAD

**Issue by Yellowshuohahaha** [isl-org/Open3D-ML#240]
My point cloud data only have three dimensions(x, y, z), and it seems that the downloaded pretrained Semantic3d model didn't work.

Here is the code:

`def get_custom_data(pc_names, path):
        pc_data = []
        for i, name in enumerate(pc_names):
            pc_path = join(path, 'points', name + '.npy')
            label_path = join(path, 'labels', name + '.npy')
            point = np.load(pc_path)
            label = np.zeros((len(point), 1))
            data = {
                'point': point,
                'feat': None,
                'label': label,
            }
            pc_data.append(data)
        return pc_data

def main():
      kitti_labels = ml3d.datasets.Semantic3d.get_label_to_names()
      v = ml3d.vis.Visualizer()
      lut = ml3d.vis.LabelLUT()
      for val in sorted(kitti_labels.keys()):
           lut.add_label(kitti_labels[val], val)
      v.set_lut("labels", lut)
      v.set_lut("pred", lut)
      ckpt_path = ‘path/pretrained semantic3d model’
      model = ml3d.models.RandLANet(ckpt_path=ckpt_path)
      pipeline_r = ml3d.pipelines.SemanticSegmentation(model)
      pipeline_r.load_ckpt(model.cfg.ckpt_path)
      ckpt_path = ‘path/pretrained semantic3d model’
      model = ml3d.models.KPFCNN(ckpt_path=ckpt_path, in_radius=10)
      pipeline_k = ml3d.pipelines.SemanticSegmentation(model)
      pipeline_k.load_ckpt(model.cfg.ckpt_path)
      data_path = example_dir + "/demo_data"
      pc_names = ["1", "2"]
      pcs = get_custom_data(pc_names, data_path)
      pcs_with_pred = pred_custom_data(pc_names, pcs, pipeline_r, pipeline_k)
      v.visualize(pcs_with_pred)`

![image](https://user-images.githubusercontent.com/48409315/111586118-50f97980-87fb-11eb-897d-9da9ec421f3c.png)

**Comment by hduonggithub** [comment]
@Yellowshuohahaha 

I think the problem is at input dimension

You can change the 'feat' to array of [:, 3] , it should run

Option 1:
feat = point or RGB

Option 2:
feat = np.zeros((len(point), 3))

label = np.zeros((len(point), 1))
data = {
'point': point,
'feat': feat,
'label': label,
}
