### ISSUE TITLE
 NameError: name 'diff' is not defined. when I inference my own data

### ISSUE THREAD

**Issue by ddm775782401** [isl-org/Open3D-ML#250]
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-39-53889c6f1e07> in <module>
      7 pc_data.append(data)
      8 cur=pc_data[0]
----> 9 results_r=pipeline_r.run_inference(cur)

~/anaconda3/envs/open3d/lib/python3.7/site-packages/open3d/_ml3d/torch/pipelines/semantic_segmentation.py in run_inference(self, data)
    165 
    166         with torch.no_grad():
--> 167             for step, inputs in enumerate(infer_loader):
    168                 results = model(inputs['data'])
    169                 self.update_tests(infer_sampler, inputs, results)

~/anaconda3/envs/open3d/lib/python3.7/site-packages/torch/utils/data/dataloader.py in __next__(self)
    361 
    362     def __next__(self):
--> 363         data = self._next_data()
    364         self._num_yielded += 1
    365         if self._dataset_kind == _DatasetKind.Iterable and \

~/anaconda3/envs/open3d/lib/python3.7/site-packages/torch/utils/data/dataloader.py in _next_data(self)
    401     def _next_data(self):
    402         index = self._next_index()  # may raise StopIteration
--> 403         data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
    404         if self._pin_memory:
    405             data = _utils.pin_memory.pin_memory(data)

~/anaconda3/envs/open3d/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py in fetch(self, possibly_batched_index)
     42     def fetch(self, possibly_batched_index):
     43         if self.auto_collation:
---> 44             data = [self.dataset[idx] for idx in possibly_batched_index]
     45         else:
     46             data = self.dataset[possibly_batched_index]

~/anaconda3/envs/open3d/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py in <listcomp>(.0)
     42     def fetch(self, possibly_batched_index):
     43         if self.auto_collation:
---> 44             data = [self.dataset[idx] for idx in possibly_batched_index]
     45         else:
     46             data = self.dataset[possibly_batched_index]

~/anaconda3/envs/open3d/lib/python3.7/site-packages/open3d/_ml3d/torch/dataloaders/torch_dataloader.py in __getitem__(self, index)
     95 
     96         if self.transform is not None:
---> 97             data = self.transform(data, attr)
     98 
     99         inputs = {'data': data, 'attr': attr}

~/anaconda3/envs/open3d/lib/python3.7/site-packages/open3d/_ml3d/torch/models/randlanet.py in transform(self, data, attr, min_possibility_idx)
    162             label=label,
    163             search_tree=tree,
--> 164             num_points=self.cfg.num_points)
    165 
    166         label = label[selected_idxs]

~/anaconda3/envs/open3d/lib/python3.7/site-packages/open3d/_ml3d/datasets/samplers/semseg_spatially_regular.py in _random_centered_gen(**kwargs)
     84                     if (pc.shape[0] < num_points):
     85                         idxs = np.array(range(pc.shape[0]))
---> 86                         idxs = list(idxs) + list(random.choices(idxs, k=diff))
     87                     else:
     88                         idxs = search_tree.query(center_point,

NameError: name 'diff' is not defined

**Comment by equant** [comment]
I have run into this issue too, using `vis_pred.py`.  The script works with the example KITTI data, but when I use my own data I get the same error you got.

**Comment by juwoojung** [comment]
I had the same issue. I don't know the exact cause, but when I reinstalled python and open3d with different versions, it worked fine.

$ conda create --name open3d-ml python=3.6.9
$ conda activate open3d-ml
$ pip install --upgrade pip
$ pip install open3d==0.11.2

**Comment by accelaire** [comment]
In version 0.12, to what does this variable 'diff' refers to ? To me it's the difference between num_points and pc.shape[0]. Although I made this correction, there are other issues later in the code:

> Traceback (most recent call last):
  File "vis_pred_rlnet.py", line 124, in <module>
    main()
  File "vis_pred_rlnet.py", line 117, in main
    pcs_with_pred = pred_custom_data(pc_names, pcs, pipeline_r)
  File "vis_pred_rlnet.py", line 54, in pred_custom_data
    results_r = pipeline_r.run_inference(data)
  File "/home/a/o3d/lib/python3.7/site-packages/open3d/_ml3d/torch/pipelines/semantic_segmentation.py", line 169, in run_inference
    self.update_tests(infer_sampler, inputs, results)
  File "/home/a/o3d/lib/python3.7/site-packages/open3d/_ml3d/torch/pipelines/semantic_segmentation.py", line 272, in update_tests
    self.test_labels[self.curr_cloud_id])
  File "/home/a/o3d/lib/python3.7/site-packages/open3d/_ml3d/torch/models/randlanet.py", line 145, in update_probs
    1 - self.test_smooth) * probs
ValueError: operands could not be broadcast together with shapes (4,19) (45056,19) 

From what i've seen before, it's most likely to be an incompatibility with the new numpy update 1.20.. but it's just a thought. Exemple: the version 0.11.2 from open3d didn't work well with this version 1.20.

**Comment by aeioaeu** [comment]
In my environment, I had the same problem when targeting less than 217893 points, but succeeded when targeting more than 217893 points.

**Comment by eiiijiiiy** [comment]
Same as @accelaire, after the 'diff' correction, I also met the broadcast shape error.

I guess that this is a shape problem. 

The `inputs['data']['point_inds']`in the function `update_probs(self, inputs, results, test_probs, test_labels) `of the class `RandLANet(BaseModel)` is supposed to be a tensor with a shape of (#batch, #points).
When there is a difference between the `pc.shape[0]` and the given` num_points`, the broadcast shape error raises and the `inputs['data']['point_inds'] ` is a list with a shape of (#batch, #points) (if a list can have shape).

The following updating can solve the 'diff' as well as he broadcast shape error.
In semseg_random.py:
``` python
if (pc.shape[0] < num_points):
  diff = num_points - pc.shape[0]
  idxs = np.array(range(pc.shape[0]))
  idxs = list(idxs) + list(random.choices(idxs, k=diff))
  idxs = np.asarray(idxs) # add this line
```

In semseg_spatially_regular.py
``` python
elif num_points is not None:
  if (pc.shape[0] < num_points):
      idxs = np.array(range(pc.shape[0]))
      diff = num_points - pc.shape[0] # add this line
      idxs = list(idxs) + list(random.choices(idxs, k=diff))
      idxs = np.asarray(idxs)  # and add this line

```

Hope this also works for you guys :)

**Comment by accelaire** [comment]
> Same as @accelaire, after the 'diff' correction, I also met the broadcast shape error.
> 
> I guess that this is a shape problem.
> 
> The `inputs['data']['point_inds']`in the function `update_probs(self, inputs, results, test_probs, test_labels) `of the class `RandLANet(BaseModel)` is supposed to be a tensor with a shape of (#batch, #points).
> When there is a difference between the `pc.shape[0]` and the given` num_points`, the broadcast shape error raises and the `inputs['data']['point_inds'] ` is a list with a shape of (#batch, #points) (if a list can have shape).
> 
> The following updating can solve the 'diff' as well as he broadcast shape error.
> In semseg_random.py:
> 
> ```python
> if (pc.shape[0] < num_points):
>   diff = num_points - pc.shape[0]
>   idxs = np.array(range(pc.shape[0]))
>   idxs = list(idxs) + list(random.choices(idxs, k=diff))
>   idxs = np.asarray(idxs) # add this line
> ```
> 
> In semseg_spatially_regular.py
> 
> ```python
> elif num_points is not None:
>   if (pc.shape[0] < num_points):
>       idxs = np.array(range(pc.shape[0]))
>       diff = num_points - pc.shape[0] # add this line
>       idxs = list(idxs) + list(random.choices(idxs, k=diff))
>       idxs = np.asarray(idxs)  # and add this line
> ```
> 
> Hope this also works for you guys :)

Thanks a lot @eiiijiiiy you seem to fix the issue!! Works fine for me

**Comment by sanskar107** [comment]
@eiiijiiiy Thanks for your fix. Could you open a pull request with this fix to `dev` branch?

**Comment by eiiijiiiy** [comment]
@sanskar107 Sure! I have already opened it (#267).
