### ISSUE TITLE
AttributeError: module 'open3d' has no attribute '__DEVICE_API__'

### ISSUE THREAD

**Issue by who1129** [isl-org/Open3D-ML#255]
I tried to install opne3d-ml on nvidia docker container. 

<lib version>
tensorflow == 2.4
open3d ==0.12
python 3.8.5

<gpu>
RTX 3090 ti

But I got this error.. 

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/open3d/ml/__init__.py", line 29, in <module>
    if _open3d.__DEVICE_API__ == 'cuda':
AttributeError: module 'open3d' has no attribute '__DEVICE_API__'

**Comment by ssheorey** [comment]
Hi @who1129 we don't support RTX3090 (Ampere GPUs) as yet. It's targeted for the next release.

**Comment by ssheorey** [comment]
@who1129 Can you retry with Open3D 0.13+ ? Ampere GPUs are now supported.
