### ISSUE TITLE
custom dataset issue

### ISSUE THREAD

**Issue by samux87** [isl-org/Open3D-ML#273]
Hi Guys, 

I'm trying to create a new dataset class called Van  but I'm having some issues when I call this command:

```
import open3d.ml.torch as ml3d
dataset = ml3d.datasets.Van()
```

and the error is:

`AttributeError: module 'open3d.ml.torch.datasets' has no attribute 'Van'`

I also tried:
```
import sys
sys.path.append('/media/sam/grosso/OneDrive/ML/pointNet/Open3D-ML/ml3d/datasets')
import van
```

but I got:
`ImportError: attempted relative import with no known parent package`

Any idea how to solve this?

Thank you,
Sam.

**Comment by sanskar107** [comment]
@samux87 you have to also add an entry in `ml3d/datasets/__init__.py`.
Also make sure you run `source set_open3d_ml_root.sh` to use cloned Open3D-ML instead of the one from the installed wheel.

**Comment by samux87** [comment]
it worked! 

Now I have a new issue:

```
bash randlanet_van.sh torch /media/sam/grosso/Datasets/roadmarking/van_open3d
Using external Open3D-ML in /media/sam/grosso/OneDrive/ML/pointNet/Open3D-ML
regular arguments
cfg_dataset: null
cfg_file: ml3d/configs/van.yml
cfg_model: null
cfg_pipeline: null
ckpt_path: null
dataset: null
dataset_path: /media/sam/grosso/Datasets/roadmarking/van_open3d
device: gpu
framework: torch
main_log_dir: null
model: null
pipeline: SemanticSegmentation
split: train

extra arguments
{}

INFO - 2021-05-13 16:24:58,508 - semantic_segmentation - DEVICE : cuda
INFO - 2021-05-13 16:24:58,508 - semantic_segmentation - Logging in file : ./logs/RandLANet_Van_torch/log_train_2021-05-13_16:24:58.txt
INFO - 2021-05-13 16:24:58,509 - van - Found 1 pointclouds for train
preprocess:   0%|                                                                   | 0/1 [00:00<?, ?it/s]POINTS SHAPE:  (54853907, 3)
labels SHAPE:  (54853907,)
preprocess: 100%|███████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.26it/s]
INFO - 2021-05-13 16:24:58,954 - van - Found 1 pointclouds for validation
INFO - 2021-05-13 16:24:58,955 - semantic_segmentation - Initializing from scratch.
2021-05-13 16:24:59.038683: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
INFO - 2021-05-13 16:24:59,645 - semantic_segmentation - Writing summary in train_log/00032_RandLANet_Van_torch.
INFO - 2021-05-13 16:24:59,646 - semantic_segmentation - Started training
INFO - 2021-05-13 16:24:59,646 - semantic_segmentation - === EPOCH 0/100 ===
training:   0%|                                                                    | 0/50 [00:00<?, ?it/s]/media/sam/grosso/OneDrive/ML/pointNet/Open3D-ML/ml3d/torch/models/randlanet.py:450: UserWarning: Mixed memory format inputs detected while calling the operator. The operator will output channels_last tensor even if some of the inputs are not in channels_last format. (Triggered internally at  /pytorch/aten/src/ATen/native/TensorIterator.cpp:924.)
  result = m_leakyrelu(f_pc + shortcut)
training: 100%|███████████████████████████████████████████████████████████| 50/50 [00:17<00:00,  2.84it/s]
/home/sam/anaconda3/envs/semanticKitti/lib/python3.8/site-packages/torch/optim/lr_scheduler.py:118: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  warnings.warn("Detected call of `lr_scheduler.step()` before `optimizer.step()`. "
validation: 100%|█████████████████████████████████████████████████████████| 10/10 [00:01<00:00,  5.35it/s]
valid acc:  []
valid_losses:  []
valid_conf_m:  []
SELF.valid_conf_m:  []
valid_conf_m:  0.0
Traceback (most recent call last):
  File "scripts/run_pipeline.py", line 134, in <module>
    main()
  File "scripts/run_pipeline.py", line 130, in main
    pipeline.run_train()
  File "/media/sam/grosso/OneDrive/ML/pointNet/Open3D-ML/ml3d/torch/pipelines/semantic_segmentation.py", line 426, in run_train
    self.save_logs(writer, epoch)
  File "/media/sam/grosso/OneDrive/ML/pointNet/Open3D-ML/ml3d/torch/pipelines/semantic_segmentation.py", line 466, in save_logs
    valid_total_acc = np.sum(np.diag(valid_conf_m)) / np.sum(valid_conf_m)
  File "<__array_function__ internals>", line 5, in diag
  File "/home/sam/anaconda3/envs/semanticKitti/lib/python3.8/site-packages/numpy/lib/twodim_base.py", line 285, in diag
    raise ValueError("Input must be 1- or 2-d.")
ValueError: Input must be 1- or 2-d.
```

It seems like that the loss wasn't calculated. Idk.

Sam.

**Comment by sanskar107** [comment]
Could you try with `dev` branch? All the latest fixes are in dev branch.

**Comment by samux87** [comment]
I cloned the dev branch and typed: 
`python -c "import open3d.ml.torch as ml3d"
`
this is the output:
`ImportError: cannot import name 'furthest_point_sampling' from 'open3d.ml.torch.ops' (/home/sam/anaconda3/envs/semanticKitti/lib/python3.8/site-packages/open3d/ml/torch/ops/__init__.py)`

Maybe I need to reinstall open3d in a different way? IDK.

Thank you again,
Sam.

**Comment by sanskar107** [comment]
Ahh, these ops are available in latest Open3D which will be released within a week. Either you can build Open3D from source, or as a workaround you can comment out every other model from `ml3d/torch/models/__init__,py`

**Comment by hduonggithub** [comment]
Hi @samux87,

I am working with S3DIS dataset. Train and testing works well. If I want to inference for my own point cloud, do I have to define a custom dataset? Thanks!

**Comment by samux87** [comment]
Hi @hduonggithub, I have tried with this script https://github.com/intel-isl/Open3D-ML/blob/master/examples/vis_pred.py but it the prediction are not good in my case. IDK if is it for the script or what else; maybe for you could be good.

Sam.

**Comment by sanskar107** [comment]
@hduonggithub you don't have to define any custom dataset for inference. You can just import model and pipeline, then run `pipeline.run_inference(data)`, here data is a dictionary, for e.g. `data = { 'point' : pc, 'feat' : None }`

**Comment by hduonggithub** [comment]
@sanskar107 
I was able to make the run_inference(data) run on the s3dis dataset. But I got error when using my own pointcloud (mydata).

Did I miss something? Please let me know if you need any further info? Thanks

Exception has occurred: AssertionError
Wrong feature dimension, please update dim_input(3 + feature_dimension) in config
  File "/mnt/d/Open3D-ML-master/examples/hd_predict_pcd.py", line 35, in <module>
    result = pipeline.run_inference(mydata)

Below is dictionary for s3dis point cloud (data) and my point cloud (mydata)
**data**
{'point': array([[ 16.538, -14...e=float32), 'feat': array([[158., 151., ...e=float32), 'label': array([3, 3, 3, ...,...ype=int32)}
special variables
function variables
'point':array([[ 16.538, -14.925,   2.169],
       [ 16.52 , -14.898,   2.264],
       [ 16.52 , -14.91 ,   2.228],
       ...,
       [ 11.424, -12.847,   1.114],
       [ 11.417, -12.86 ,   1.106],
       [ 11.442, -12.846,   1.101]], dtype=float32)
'feat':array([[158., 151., 133.],
       [123., 109.,  80.],
       [136., 125., 105.],
       ...,
       [150., 153., 134.],
       [164., 165., 159.],
       [154., 156., 142.]], dtype=float32)
'label':array([3, 3, 3, ..., 5, 5, 5], dtype=int32)
len():3

**mydata**
{'point': array([[ 1.09335744,...0540537]]), 'feat': None, 'label': array([0., 0., 0., ...., 0., 0.])}
special variables
function variables
'point':array([[ 1.09335744, -4.53015947,  0.01575116],
       [ 0.39287063, -4.74703026,  0.01600954],
       [ 0.92600238, -4.37050104,  0.01555619],
       ...,
       [ 3.70381791,  0.01171056,  0.54572443],
       [ 3.70335974,  0.00764537,  0.54506585],
       [ 3.82367326,  0.0151082 ,  0.50540537]])
'feat':None
'label':array([0., 0., 0., ..., 0., 0., 0.])
len():3

**Comment by samux87** [comment]
Hi @sanskar107, if I would like to use x,y,z + intensity in my dataset; what I have to change?

I tried to:
- change in the .yml file 
`dim_input: 4`
- change in mydataset.py under get_data
```
        data = {
            'point': points,
            'feat': intensity, 
            'label': labels
        }
```
I lunched the training script and I got:
```
Traceback (most recent call last):
  File "scripts/run_pipeline.py", line 145, in <module>
    main()
  File "scripts/run_pipeline.py", line 141, in main
    pipeline.run_train()
  File "/media/sam/grosso/OneDrive/ML/pointNet/Open3D-ML/ml3d/torch/pipelines/semantic_segmentation.py", line 374, in run_train
    for step, inputs in enumerate(tqdm(train_loader, desc='training')):
  File "/home/sam/anaconda3/envs/semanticKitti/lib/python3.8/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/sam/anaconda3/envs/semanticKitti/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/sam/anaconda3/envs/semanticKitti/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 403, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/sam/anaconda3/envs/semanticKitti/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/sam/anaconda3/envs/semanticKitti/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/media/sam/grosso/OneDrive/ML/pointNet/Open3D-ML/ml3d/torch/dataloaders/torch_dataloader.py", line 97, in __getitem__
    data = self.transform(data, attr)
  File "/media/sam/grosso/OneDrive/ML/pointNet/Open3D-ML/ml3d/torch/models/randlanet.py", line 184, in transform
    assert cfg.dim_input == feat.shape[
AssertionError: Wrong feature dimension, please update dim_input(3 + feature_dimension) in config

```

Did I something wrong?

Thank you,
Samuele.

**Comment by sanskar107** [comment]
@samux87 your changes should work. Can you print the shape of `feat` right before this assertion statement in `randlanet.py`?
