### ISSUE TITLE
Regarding the release of the latest version

### ISSUE THREAD

**Issue by luoxiaoliaolan** [isl-org/Open3D-ML#284]
Thank you for your outstanding work！
   Open3D 0.12.0 has been released for several months，and when will the latest version of open3d be released? Currently open3d-ML supports some tasks related to 3D semantic segmentation and object detection but the supported algorithms and functions are still relatively limited, Will the newly released version add support for this part of the function?
I look forward to your team releasing the latest version soon.

**Comment by sanskar107** [comment]
@luoxiaoliaolan the latest version will be released within a week.

**Comment by luoxiaoliaolan** [comment]
Thank you very much for your team’s work and look forward to the new version with more powerful features.
