### ISSUE TITLE
[ML3D Visualizer] How to make all checkboxes checked initially ?

### ISSUE THREAD

**Issue by yucedagonurcan** [isl-org/Open3D-ML#291]
Hello all,

It's rather a easy question. I am visualizing custom data with the help of the https://github.com/intel-isl/Open3D-ML/blob/master/docs/howtos.md#visualize-custom-data.

I have many pcds and bounding boxes with respect to them. 

From what I understand is that I need to create a custom dataset for this behaviour, because standard data visualization is not handling bounding boxes and frame relationships(They are not played together, they have no relationship). 

I changed the visualizer script so that they are related to each other but now _**I want all the checkboxes to be pre-checked.**_

![image](https://user-images.githubusercontent.com/16342629/120701383-6eb1b300-c4bb-11eb-93ba-c890b9a92c45.png)

What is the cleanest way to do that? 

Have a great day.

**Comment by sanskar107** [comment]
@yucedagonurcan you can change two lines here
https://github.com/intel-isl/Open3D-ML/blob/master/ml3d/vis/visualizer.py#L1581
Set L1581, and L1582 to `True`

**Comment by yucedagonurcan** [comment]
Hello @sanskar107, thank you for your reply.

> @yucedagonurcan you can change two lines here
> https://github.com/intel-isl/Open3D-ML/blob/master/ml3d/vis/visualizer.py#L1582
> Set L1582, and L1583 to `True`

I already tried that change, here is what I get. I want Open3D to load pointclouds also:


https://user-images.githubusercontent.com/16342629/120920396-3383cf80-c6c7-11eb-836d-39795daa08f5.mp4

**Comment by sanskar107** [comment]
@yucedagonurcan loading every point may result in exhausting all of the memory available. We define a memory limit, which you can change, to load multiple points. See https://github.com/isl-org/Open3D-ML/blob/master/ml3d/vis/visualizer.py#L255
