### ISSUE TITLE
Open3D 0.13 with Torch 1.8.1

### ISSUE THREAD

**Issue by fabiopoiesi** [isl-org/Open3D-ML#297]
Hi,

is there are a way to use Open3D 0.13 with Torch 1.8.1?

Thanks!

ps.
this would be **very** important because with torch 1.8, they finally solved the issue of slow svd on gpu.
here below some of my tests.

tested code:
```
import torch
import time

a = torch.rand((500, 3, 3), device='cuda')
t = time.time()
_, _, v = torch.svd(a)
print('on gpu {:.6f}'.format(time.time() - t))


b = torch.rand((500, 3, 3), device='cpu')
t = time.time()
_, _, v = torch.svd(b)
print('on cpu {:.6f}'.format(time.time() - t))
```

results using torch 1.7.1:
```
on gpu 0.672839
on cpu 0.002409
```

results using torch 1.8.1:
```
on gpu 0.002846s
on cpu 0.001417s
```

**Comment by sanskar107** [comment]
@fabiopoiesi You can build Open3D from source with Torch 1.8.1.
1) Clone Open3D.
2) `source Open3D-ML/set_open3d_ml_root.sh`
2) build Open3D and pass `-DBUNDLE_OPEN3D_ML=ON` to cmake.

**Comment by fabiopoiesi** [comment]
Thanks.
I have to install it on a computer on which I do not have root rights, so installing dependencies is always painful.
Is there a way to build it from source on a computer with similar configuration and then install it on the other?

**Comment by sanskar107** [comment]
Yes, you can build Open3D on a different computer and create pip package which you can install anywhere.
You can run `make pip-package` to create wheel after running cmake.

**Comment by fabiopoiesi** [comment]
I'm trying to compile and I have the first errors.
Here is how I configured cmake.

![Screenshot from 2021-06-21 13-42-41](https://user-images.githubusercontent.com/17005352/122756381-a2038880-d296-11eb-9ae3-7873e1af22fd.png)

All fine until I got this error at 86%:
```
Open3D/cpp/open3d/ml/pytorch/sparse_conv/SparseConvOps.cpp:191:56: error: no matching function for call to ‘at::Tensor::index(at::Tensor&)’ 
191 |        neighbors_kernel_index.index(inv_arange).contiguous();
```

Any suggestion?

**Comment by ssheorey** [comment]
@fabiopoiesi PyTorch v1.8.1 builds with the `-fno-gnu-unique` flags are now available:

https://github.com/intel-isl/open3d_downloads/releases/tag/torch1.8.1

PR #304 updates the PyTorch supported version to 1.8.1 as well.

**Comment by twmht** [comment]
@ssheorey 

torch-1.8.1-cp37-cp37m-linux_x86_64.whl is dead?
