### ISSUE TITLE
About the number of points to RandLA-Net

### ISSUE THREAD

**Issue by giants19** [isl-org/Open3D-ML#298]
Hi, Thanks for your hard work for open3d! 
I have a question about num_points. In randlanet.py, what does
"num_points=4096 * 11 (=45056),  # Number of input points"  mean?
In my understanding, 45046 points are randomly sampled from input point clouds to infer the class. 
Then, interpolation like Knn is performed to get the result to all input points. Is it correct?
Thanks in advance.

**Comment by sanskar107** [comment]
@giants19 pointcloud is downsampled by grid size(voxel_size) given as `cfg.grid_size`, then `num_points` are cropped from a random location keeping the density same. At inference time, we downsample, then we do this cropping repeatedly at different location and then interpolate for all points.

**Comment by KentaItakura** [comment]
@sanskar107 Thanks for clarifying. Well noted, thanks!
