### ISSUE TITLE
To extract confusion matrix and accuracy of each class

### ISSUE THREAD

**Issue by StellaLulu** [isl-org/Open3D-ML#300]
Hi! Thanks for all the hard work for pushing the ver 0.13. 
I am currently running `RandLA` algo and wondering if there's a way to extract the confusion matrix and accuracy of each class? 

Thanks!

**Comment by sanskar107** [comment]
We have added this feature in the `dev` branch, now you can use new `SemSegMetric` class and call `obj.acc()`, `obj.iou()`, `obj.confusion_metric()` to get accuracy, IoU and confusion metric.
