### ISSUE TITLE
Pointpillars model

### ISSUE THREAD

**Issue by reddittoob** [isl-org/Open3D-ML#306]
Hi, I'm trying to run pointpillar model.

So, I tried to download pretrained model, but I got an access denied like below image

![Screenshot from 2021-06-21 15-33-06](https://user-images.githubusercontent.com/30588581/122717023-fe21d900-d2a5-11eb-8b05-b5e99eb5716a.png)
.

Anyone help?

**Comment by ArrogantNobody** [comment]
Hi sir, I am also having trouble regarding training pointpillar model, shall we have a discussion?

**Comment by sanskar107** [comment]
Thanks for reporting this. We have updated the links.
