### ISSUE TITLE
Error on using predefined script for PointPillars 

### ISSUE THREAD

**Issue by kazu0622** [isl-org/Open3D-ML#307]
I've got an error while executing this.
# Launch testing for PointPillars on KITTI with torch.
python scripts/run_pipeline.py torch -c ml3d/configs/pointpillars_kitti.yml --split test --dataset.dataset_path <path-to-dataset> --pipeline ObjectDetection --dataset.use_cache True

I'd like to know how to solve this problem.

Here is the Error.
validation: 100%|########################################| 3769/3769 [01:51<00:00, 33.91it/s]
/usr/local/lib/python3.6/dist-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)
Traceback (most recent call last):
  File "scripts/run_pipeline.py", line 145, in <module>
    main()
  File "scripts/run_pipeline.py", line 139, in main
    pipeline.run_test()
  File "/home/*****/.local/lib/python3.6/site-packages/open3d/_ml3d/torch/pipelines/object_detection.py", line 117, in run_test
    self.run_valid()
  File "/home/******/.local/lib/python3.6/site-packages/open3d/_ml3d/torch/pipelines/object_detection.py", line 190, in run_valid
    desc += " %s: %.03f" % (l, np.mean(v))
TypeError: only size-1 arrays can be converted to Python scalars

Thanks.

**Comment by abhinavagarwalla** [comment]
I get a CUDA device assert error on running validation on GPU. Did you encounter a similar issue? How did you fix that?

**Comment by kazu0622** [comment]
@abhinavagarwalla I've never experienced cuda relating issue.  I'm afraid you might need to install cuda relating software on python.

**Comment by WiNet-Lab-IIT-Hyderabad** [comment]
I got the same error. Any suggestions?

**Comment by kazu0622** [comment]
@WiNet-Lab-IIT-Hyderabad Unfortunately, I haven't got solved this issue. I guess the lack of labeling data for the test data might cause this.

**Comment by yurithefury** [comment]
Try with `pipeline.val_batch_size=2`
