### ISSUE TITLE
quick question: what is dim_feature: 8 in the yml? 

### ISSUE THREAD

**Issue by samux87** [isl-org/Open3D-ML#311]
Hi guys, 

what is dim_feature: 8 in the yml file? is it a network parameter? is it something that I have to adjust with the number of features that I put in input?

Thanks,
S.

**Comment by sanskar107** [comment]
`dim_feature` is a network parameter in RandLANet. It defines number of neurons in the first layer. You have to adjust `dim_input` depending on the number of feature dimensions you have.
