### ISSUE TITLE
is NPY the only format supported?

### ISSUE THREAD

**Issue by masterchop** [isl-org/Open3D-ML#312]
I was looking for a sample to do 3d object detection on pointcloud but i was not able to find it. is it possible with this library?
what pointcloud formats are support it and if there is a sample i can take a look.

thanks :)

**Comment by sanskar107** [comment]
@masterchop we support multiple datasets in their default pointcloud format. But if you are using some custom pointcloud, you have to use `CustomDataset` class which only supports npy at the moment. Still you can modify that class as per your requirements.
