### ISSUE TITLE
Access denied when downloading Toronto3D pretrained model + Add Toronto3D RGB to RandLAnet

### ISSUE THREAD

**Issue by fredpeertje** [isl-org/Open3D-ML#314]
I'm not able to download the pretrained model of Toronto3D using the following Url listed in the main README: [https://storage.googleapis.com/open3d-releases/model-zoo/randlanet_toronto3D_202010091306.pth](https://storage.googleapis.com/open3d-releases/model-zoo/randlanet_toronto3D_202010091306.pth)

Another question, do you plan to add code for using RGB during training ([ref.](https://github.com/QingyongHu/RandLA-Net/issues/158))

**Comment by ssheorey** [comment]
Hi @fredpeertje this is the link in the README file and it works (check utc at end):
https://storage.googleapis.com/open3d-releases/model-zoo/randlanet_toronto3d_202010091306utc.pth
