### ISSUE TITLE
Can't train Toronto3D dataset on Pytorch implementation of Randla-Net

### ISSUE THREAD

**Issue by fredpeertje** [isl-org/Open3D-ML#320]
I tried to train Randla-Net on the Toronto3D, but training does not seem to work. It is stuck on this for 10 hours now:
`training:   0%|          | 0/50 [00:00<?, ?it/s]`

I managed to run inference using the Toronto3D trained model, and this works pretty well.

The code that I use:
```
import os
import open3d.ml as _ml3d
import open3d.ml.torch as ml3d

cfg_file ="ml3d/configs/randlanet_toronto3d.yml"
cfg = _ml3d.utils.Config.load_from_file(cfg_file)

model = ml3d.models.RandLANet(**cfg.model)
cfg.dataset['dataset_path'] = "/content/drive/My Drive/Datasets/street_lights/LiDAR/benchmark_datasets/Toronto3d/"
dataset = ml3d.datasets.Toronto3D(cfg.dataset.pop('dataset_path', None), **cfg.dataset)
pipeline = ml3d.pipelines.SemanticSegmentation(model=model, dataset=dataset, max_epoch=3, batch_size=2, device='gpu')

ckpt_folder = "./logs/"
os.makedirs(ckpt_folder, exist_ok=True)

pipeline.cfg_tb = {
    "readme": "readme",
    "cmd_line": "cmd_line",
    "dataset": "Toronto3D",
    "model": "RandLaNet",
    "pipeline": "Default Pipeline",
}
pipeline.run_train()
```

The installation specs:
```
Latest version Open3D-ML
Linux OS Python Version: 3.7.11
GPU P100-PCI 16GB
CUDA Version: 11.2
torch==1.7.1+cu110
torchvision==0.8.2+cu110
open3d==0.13.0
```

**Comment by fredpeertje** [comment]
FYI. Unlike Pytorch, the Tensorflow implementation works... It makes use of the full 16GB GPU memory with a batch size of 1.

**Comment by IMSHJI** [comment]
I also had the same issue as you.

I tried this code:
python scripts/run_pipeline.py torch -c ml3d/configs/randlanet_semantickitti.yml --dataset.dataset_path <path-to-dataset> --pipeline SemanticSegmentation --dataset.use_cache True

this code appears in the Using predefined scripts part of the Open3D-ML main page.

I tried KPConv, RandLA-Net model on SemanticKITTI dataset, but it is not progressing at 0%. (As a result of watching for 12 hours)
Preprocessing process went without problems. Problems arise in training after preprocessing.

The installation specs:
python: 3.6.13
tensorflow: 2.4.2
CUDA Version: 11.3
torch: 1.7.1-cp36
torchvision: 0.8.2+cu110
open3d: 0.13.0

![스크린샷, 2021-07-22 17-06-19](https://user-images.githubusercontent.com/76108208/126608663-093dc64b-bd7a-4ef2-84d5-983637553e86.png)

**Comment by tangpan360** [comment]
> I also had the same issue as you.
> 
> I tried this code:
> python scripts/run_pipeline.py torch -c ml3d/configs/randlanet_semantickitti.yml --dataset.dataset_path --pipeline SemanticSegmentation --dataset.use_cache True
> 
> this code appears in the Using predefined scripts part of the Open3D-ML main page.
> 
> I tried KPConv, RandLA-Net model on SemanticKITTI dataset, but it is not progressing at 0%. (As a result of watching for 12 hours)
> Preprocessing process went without problems. Problems arise in training after preprocessing.
> 
> The installation specs:
> python: 3.6.13
> tensorflow: 2.4.2
> CUDA Version: 11.3
> torch: 1.7.1-cp36
> torchvision: 0.8.2+cu110
> open3d: 0.13.0
> 
> ![스크린샷, 2021-07-22 17-06-19](https://user-images.githubusercontent.com/76108208/126608663-093dc64b-bd7a-4ef2-84d5-983637553e86.png)

The same issue as you.
Do you have any idea now?

**Comment by tangpan360** [comment]
Could you try with `--pipeline.num_workers 0` ?  In my device, it works, Sometimes torch gets stuck in a deadlock while using custom operators.

Great answer from Sanskar Agrawa.

**Comment by fredpeertje** [comment]
I Switched to the official RandLA-Net code, no issues with that code!
