### ISSUE TITLE
Training object detection on custom dataset

### ISSUE THREAD

**Issue by ArrogantNobody** [isl-org/Open3D-ML#322]
Hi! I am a new user for open3d-ML, is it possible for users to train an object detection model on their own dataset? Do we have a tutorial like training semantic segmentation?

**Comment by ArrogantNobody** [comment]
Or anyone has some experience, could you please give me some guidance?

**Comment by sanskar107** [comment]
@ArrogantNobody you can define your own dataset class or you can modify `ml3d/datasets/customdataset.py` to support your dataset. You can then define your config file similar to ones present in `ml3d/configs/`.
