### ISSUE TITLE
How to make the 3d bbox visualize like the point cloud for Animation

### ISSUE THREAD

**Issue by PrinceVictor** [isl-org/Open3D-ML#329]
Dear open3D team!
I try to call the class Visualizer() to animate visualize the point cloud and 3d bounding box. For animation, the point cloud can show frame by frame, but the whole bounding boxes are shown on the GUI. I notice your video about open3D-ml on Youtube can visualize the pointcloud and 3d boundingbox sync. What should I do to visualize boundingbox like point cloud frame by frame?
![2021-07-30 15-04-19屏幕截图](https://user-images.githubusercontent.com/30308024/127614832-b4e9db43-f27e-4dc3-b2e0-b20f69126049.png)

**Comment by fergcd** [comment]
@PrinceVictor I also want to animate 3d bbox frames.  Did you find how to do that?

**Comment by fergcd** [comment]
I found example python script!
https://github.com/isl-org/Open3D-ML/pull/392/commits/ea390f0c805ea3f5d36d4a9687bc1970438105cc
