### ISSUE TITLE
UnboundLocalError: local variable 'pred' referenced before assignment when running predefined script for testing

### ISSUE THREAD

**Issue by jokokojote** [isl-org/Open3D-ML#341]
When running the predefined script for model evaluation for the SemanticKitti Dataset an `UnboundLocalError` occurs:

`python Documents/Open3D-ML/scripts/run_pipeline.py torch -c Documents/Open3D-ML/ml3d/configs/randlanet_semantickitti.yml --dataset.dataset_path '/home/pointclouduser/Documents/Data/SemanticKITTI' --pipeline SemanticSegmentation --dataset.use_cache True --split test`

Output:
```
regular arguments
batch_size: null
cfg_dataset: null
cfg_file: Documents/Open3D-ML/ml3d/configs/randlanet_semantickitti.yml
cfg_model: null
cfg_pipeline: null
ckpt_path: null
dataset: null
dataset_path: null
device: gpu
framework: torch
main_log_dir: null
max_epochs: null
mode: null
model: null
pipeline: SemanticSegmentation
split: test

extra arguments
dataset.dataset_path: /home/pointclouduser/Documents/Data/SemanticKITTI
dataset.use_cache: 'True'

INFO - 2021-08-06 10:13:12,364 - semantic_segmentation - DEVICE : cuda
INFO - 2021-08-06 10:13:12,365 - semantic_segmentation - Logging in file : ./logs/RandLANet_SemanticKITTI_torch/log_test_2021-08-06_10:13:12.txt
INFO - 2021-08-06 10:13:12,419 - semantickitti - Found 20351 pointclouds for test
preprocess: 100%|████████████████████████████| 20351/20351 [1:11:44<00:00,  4.73it/s]
INFO - 2021-08-06 11:28:36,337 - semantic_segmentation - Initializing from scratch.
INFO - 2021-08-06 11:28:36,339 - semantic_segmentation - Started testing
test 0/20351:  85%|████████████████████▍   | 68152/79845 [00:00<00:00, 186776.79it/s]Traceback (most recent call last):
  File "Documents/Open3D-ML/scripts/run_pipeline.py", line 145, in <module>
    main()
  File "Documents/Open3D-ML/scripts/run_pipeline.py", line 139, in main
    pipeline.run_test()
  File "/home/pointclouduser/Documents/Open3D-ML/venv/lib/python3.8/site-packages/open3d/_ml3d/torch/pipelines/semantic_segmentation.py", line 241, in run_test
    dataset.save_test_result(inference_result, attr)
  File "/home/pointclouduser/Documents/Open3D-ML/venv/lib/python3.8/site-packages/open3d/_ml3d/datasets/semantickitti.py", line 189, in save_test_result
    pred[pred >= ign] += 1
UnboundLocalError: local variable 'pred' referenced before assignment
test 0/20351: 100%|█████████████████████████| 79845/79845 [00:01<00:00, 54394.30it/s]
```

Open3D: 0.13.0
Python: Python 3.8.11
OS: Ubuntu 18.04 LTS

When opening `semantickitti.py` in PyCharm it shows  multiple unresolved reference errors in `save_test_result` for `pred`  (lines 189,189 and 193). There is one for `remap_lut` in `save_test_result_kpconv` (line 216) as well.

**Comment by WiNet-Lab-IIT-Hyderabad** [comment]
I too got exactly same error:

# evaluate performance on the test set; this will write logs to './logs'.
pipeline.run_test()

UnboundLocalError                         Traceback (most recent call last)
/tmp/ipykernel_19511/3964498242.py in <module>
      1 # evaluate performance on the test set; this will write logs to './logs'.
----> 2 pipeline.run_test()

/mnt/05ee6e99-db7e-4bc6-a94a-19668fe5c077/object_detection/open3dmlenv/lib/python3.7/site-packages/open3d/_ml3d/torch/pipelines/semantic_segmentation.py in run_test(self)
    239                     }
    240                     attr = self.dataset_split.get_attr(test_sampler.cloud_id)
--> 241                     dataset.save_test_result(inference_result, attr)
    242 
    243         log.info("Finshed testing")

/mnt/05ee6e99-db7e-4bc6-a94a-19668fe5c077/object_detection/open3dmlenv/lib/python3.7/site-packages/open3d/_ml3d/datasets/semantickitti.py in save_test_result(self, results, attr)
    187         test_file_name = name_points
    188         for ign in cfg.ignored_label_inds:
--> 189             pred[pred >= ign] += 1
    190 
    191         store_path = join(save_path, name_points + '.label')

UnboundLocalError: local variable 'pred' referenced before assignment

Could you find the solution?

**Comment by WiNet-Lab-IIT-Hyderabad** [comment]
I think the solution is to add:

        pred = results['predict_labels']

before,

        for ign in cfg.ignored_label_inds:
            pred[pred >= ign] += 1

in the sementickitti.py

**Comment by jokokojote** [comment]
@WiNet-Lab-IIT-Hyderabad you are right, seems to work now with your suggestion.

**Comment by ssheorey** [comment]
@WiNet-Lab-IIT-Hyderabad thanks for looking into this. Please submit a PR with the fix.
