### ISSUE TITLE
PyTorch PointPillars implementation does not do bounds checking on pointcloud voxelization, leading to invalid pseudoimage coordinates

### ISSUE THREAD

**Issue by kylevedder** [isl-org/Open3D-ML#349]
PointPillars [invokes](https://github.com/isl-org/Open3D-ML/blob/200bee315a55772a9b40f1304d9165242f896786/ml3d/torch/models/point_pillars.py#L384) Open3D's [`voxelize`](http://www.open3d.org/docs/release/python_api/open3d.ml.torch.ops.voxelize.html) with the raw input points but does [not do any out-of-bounds point filtering](https://github.com/isl-org/Open3D/blob/master/cpp/open3d/ml/impl/misc/Voxelize.h). The model intermittently generates a pillar outside of the pseudoimage, and I _think_ the root cause is out of bounds data points, but I am _certain_ the coordinates coming out of voxalize are wrong. 

In the current implementation, this issue is masked by the fact that the Scatter step is transforming these 2D coordinates into a 1D coordinate, typically resulting in the pillar being placed on a coordinate somewhere else in the pseudoimage; however, this also rarely fails as coordinates still sometimes end up off the end of the 1D array.

To demonstrate this error, I have added two assert statements to the `voxelize` call in `point_pillars.py` doing axis bounds checking which fail once every couple epochs:

```
        num_voxels = (self.points_range_max - self.points_range_min) / self.voxel_size
        ans = voxelize(points=points, 
                       voxel_size=self.voxel_size, 
                       points_range_min=self.points_range_min,
                       points_range_max=self.points_range_max, 
                       max_points_per_voxel=self.max_num_points, 
                       max_voxels=max_voxels)

        out_coords = ans.voxel_coords[:, [2, 1, 0]].contiguous()
        in_bounds_x = out_coords[:, 1] < num_voxels[1]
        in_bounds_y = out_coords[:, 2] < num_voxels[0]
        assert(in_bounds_x.all())
        assert(in_bounds_y.all())
```

Two possible solutions:

1) Do point filtering before `voxelize` is called
2) Reject invalid coordinates and their associated pillars after `voxelize` is called

I think 2) would be faster given it's `int` comparisons on less data, so I am going to submit a PR to fix this shortly.

**Comment by kylevedder** [comment]
I confirmed that points are fairly regularly outside the bounds of the pseudoimage, but often these are single points that are not selected for pillar generation which is why this is such a rare occurrence.

**Comment by sanskar107** [comment]
@kylevedder Could you reproduce this error with equality sign as well ? i.e.
`in_bounds_x = out_coords[:, 1] <= num_voxels[1]`
`in_bounds_y = out_coords[:, 2] <= num_voxels[0]`

This is the voxel_coords function in voxelize op: `auto coords = ((point - points_range_min_vec) * inv_voxel_size)`
Consider a point which is equal to `points_range_max`, it will result in voxel_coords equal to num_voxels and fail your assertion.

Secondly, could you share your CUDA and PyTorch version ? There is a known issue of Pytorch with CUDA 11 which may result in some invalid output from the voxelize op.

**Comment by kylevedder** [comment]
@sanskar107 the voxelization code definitely has issues as the coordinates generated were sometimes 30+ pillars outside the bounds of the PointPillars pseudoimage in the above example.

If generating points at with a coordinate of `num_voxels[0]` or `num_voxels[1]` is expected behavior, the PointPillars implementation wrong; it should be asking for a smaller range that does not allow for a valid coordinate to contain`num_voxels[0]` or `num_voxels[1]`. The pseudoimage is of size `num_voxels[0], num_voxels[1]` by construction and thus the valid coordinate indices should be from `0` to `num_voxels[0]` for X and `0` to `num_voxels[1]` for Y; the call to voxelize should be updated to reduce the valid output range.

System info:
nvcc/CUDA version: 11.1.105
NVidia Driver Version: 460.80 (CUDA 11.2)
PyTorch Version: 1.7.1 (this version is the compiled from source version provided by Open3D)
Open3D Version: 0.13.0 (installed via pip; no CUDA support)
