### ISSUE TITLE
FileNotFoundError: File /ml3d/configs/randlanet_semantickitti.yml not found

### ISSUE THREAD

**Issue by Ed0flower93** [isl-org/Open3D-ML#351]
Hi, I am trying to use open3d and I can open the "reading datasets" correctly. 
But when I try the "loading config file" I get this error:

Traceback (most recent call last):
  File "/home/edoardo/Documenti/Open3D_documents/Loading_config_file.py", line 6, in <module>
    cfg = _ml3d.utils.Config.load_from_file(cfg_file)
  File "/home/edoardo/.local/lib/python3.6/site-packages/open3d/_ml3d/utils/config.py", line 212, in load_from_file
    raise FileNotFoundError(f'File {filename} not found')
FileNotFoundError: File /ml3d/configs/randlanet_semantickitti.yml not found

I've tried changing the path but I can't figure out where the error is. I hope for your help.

Thanks

**Comment by kylevedder** [comment]
Is `ml3d/configs/randlanet_semantickitti.yml` the correct relative path to that config file? To sanity check it is, you ought to be able to run `ls ml3d/configs/randlanet_semantickitti.yml` from within the same folder as your script.

I suspect your custom script is sitting inside another folder and `ml3d/configs/randlanet_semantickitti.yml` is not the correct relative path to that config file.

**Comment by Ed0flower93** [comment]
Thank you very much, now it works.
I have also another problem with the semantic segmentation script:

import os
import open3d._ml3d as _ml3d
import open3d.ml3d.torch as ml3d

cfg_file = "ml3d/configs/randlanet_semantickitti.yml"
cfg = _ml3d.utils.Config.load_from_file(cfg_file)

model = ml3d.models.RandLANet(**cfg.model)
cfg.dataset['dataset_path'] = "media/edoardo/LaCie/data_odometry_velodyne"
dataset = ml3d.datasets.SemanticKITTI(cfg.dataset.pop('dataset_path', None), **cfg.dataset)
pipeline = ml3d.pipelines.SemanticSegmentation(model, dataset=dataset, device="gpu", **cfg.pipeline)

The error is the following one:

Traceback (most recent call last):
  File "/home/edoardo/.local/lib/python3.6/site-packages/open3d/Semantic_segmentation.py", line 10, in <module>
    dataset = ml3d.datasets.SemanticKITTI(cfg.dataset.pop('dataset_path', None), **cfg.dataset)
AttributeError: module 'open3d.ml3d.torch' has no attribute 'datasets'

I already tried to add the dataset foldet to the torch folder but it is still there.

Thanks again for your support

**Comment by kylevedder** [comment]
It should be `import open3d.ml.torch as ml3d`. 

As a test of this, I was able to run the following script
```
python -c "import open3d.ml.torch as ml3d; foo = ml3d.datasets.SemanticKITTI; print(foo)"
```
which printed
```
<class 'ml3d.datasets.semantickitti.SemanticKITTI'>
```

**Comment by kylevedder** [comment]
This is the root cause:

>FileNotFoundError: [Errno 2] File o directory non esistente: 'media/edoardo/LaCie/data_odometry_velodyne/dataset/sequences/11/velodyne'

Your path needs to be an absolute path to the `/media` directory but you don't have the preceding `/`; it should be `/media/edoardo/LaCie/data_odometry_velodyne/dataset/sequences/11/velodyne`

Two of the errors you have written about in this thread have stemmed from incorrect relative or absolute file paths. I suggest that you read up on how relative and absolute file paths work so that you don't need to ask other people how to fix these "file not found" issues.

**Comment by Ed0flower93** [comment]
You're right, so I'll only bother you for important things.
One last thing, is it possible to acquire and create your own datasets with a depth camera such as the intel realsense d435?

Thank you very much

**Comment by kylevedder** [comment]
Yes, see `ml3d/datasets/customdataset.py` in this repo for details.
