### ISSUE TITLE
 RandLANet Tensorflow Performance Degradation on SemanticKITTI

### ISSUE THREAD

**Issue by KhaledSaleh** [isl-org/Open3D-ML#360]
I'm using the pre-trained RandLANet Tensorflow model from the model zoo to evaluate the validation split of the SemanticKITTI instead of the test split.

The only modification I have done was to replace data split from 'test' to 'validation' in the following line:
https://github.com/isl-org/Open3D-ML/blob/fe5f21917c39a40ff82d35ad8aab4016d35ec738/ml3d/tf/pipelines/semantic_segmentation.py#L161 

As per issue#168, I was expecting to an have an overall IOU more than 0.50 however I only get an overall IOU of 0.267. 

I have made sure to use the latest release of Open3D-ML (0.13) with Tensorflow 2.4. 

Are there any additional modifications needed to reproduce the same/comparable performance to the ones reported in the model zoo?

**Comment by sanskar107** [comment]
@KhaledSaleh thanks for reporting, I'll try to reproduce this issue. Please make sure you are using config files from `ml3d/configs/randlanet_semantickitti.yml`

**Comment by KhaledSaleh** [comment]
Thanks @sanskar107 for your reply. I can confirm that I was using the config file `ml3d/configs/randlanet_semantickitti.yml`.

**Comment by sanskar107** [comment]
@KhaledSaleh This issue has been fixed in latest `dev` branch. Could you verify the same?
