### ISSUE TITLE
Performance issues in the definition of get_batch_gen, ml3d/tf/models/point_pillars.py(P1)

### ISSUE THREAD

**Issue by DLPerf** [isl-org/Open3D-ML#363]
Hello, I found a performance issue in the definition of `get_batch_gen`, ml3d/tf/models/point_pillars.py, [`tf.zeros((0, 7)`](https://github.com/isl-org/Open3D-ML/blob/fe5f21917c39a40ff82d35ad8aab4016d35ec738/ml3d/tf/models/point_pillars.py#L340) will be called repeatedly during program execution, resulting in reduced efficiency. I think it should be created before the loop.

The same issues exist in:

- [`tf.zeros((0,)` in line 345](https://github.com/isl-org/Open3D-ML/blob/fe5f21917c39a40ff82d35ad8aab4016d35ec738/ml3d/tf/models/point_pillars.py#L345)
- [`tf.zeros((0,)` in line 358](https://github.com/isl-org/Open3D-ML/blob/fe5f21917c39a40ff82d35ad8aab4016d35ec738/ml3d/tf/models/point_pillars.py#L358)
- [`tf.zeros((0, 7)` in line 434](https://github.com/isl-org/Open3D-ML/blob/fe5f21917c39a40ff82d35ad8aab4016d35ec738/ml3d/tf/models/point_rcnn.py#L434)

Looking forward to your reply. Btw, I am very glad to create a PR to fix it if you are too busy.

**Comment by sanskar107** [comment]
@DLPerf thanks for reporting this issue. Feel free to create a fix for this.
