### ISSUE TITLE
Error (403 Forbidden error) while downloding the weights of pointpillars model

### ISSUE THREAD

**Issue by Sri20021** [isl-org/Open3D-ML#371]
I get the 403 forbidden error while downloading the weights through the link: https://storage.googleapis.com/open3d-releases/model-zoo/pointpillars_kitti_202012171738utc.pth
I find the same issue even when downloading through the browser
Request you to check and correct this.

**Comment by sanskar107** [comment]
Thanks for reporting this issue. The link has been updated in master. Please use this link 
https://storage.googleapis.com/open3d-releases/model-zoo/pointpillars_kitti_202012221652utc.pth
