### ISSUE TITLE
Wrong filename in model_weights.txt for randlanet & semantickitti tensorflow checkpoints

### ISSUE THREAD

**Issue by jokokojote** [isl-org/Open3D-ML#373]
In https://storage.googleapis.com/open3d-releases/model-zoo/model_weights.txt is a small mistake: 

The file:
`randlanet_semantickitti_202009090354utc.zip `
does not exist, I think 
`randlanet_semantickitti_202010091306.zip`
would be right, like it is linked in the table in model_zoo.md.

I can not fix it myself (I guess), cause model_weights.txt is an external file.

**Comment by sanskar107** [comment]
Thanks for reporting this. Fixed
