### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by kukuruza** [isl-org/Open3D-ML#376]
Is there a documentation on the architecture somewhere? I am trying to study the codebase, but there are few comments, and there are no docs.

In particular, I'm trying to understand one simple thing - when training / testing the semantic segmentation pipeline (with randlanet or kpconv models) on SemanticKITTI, do point clouds from several samples in the same sequence get merged together, or are they completely independent?

**Comment by kukuruza** [comment]
> In particular, I'm trying to understand one simple thing - when training / testing the semantic segmentation pipeline (with randlanet or kpconv models) on SemanticKITTI, do point clouds from several samples in the same sequence get merged together, or are they completely independent?

Seems like the answer is INDEPENDENT for RANDLANET because the file `poses.txt` is not used, and it is impossible to merge point clouds without this file.

**Comment by sanskar107** [comment]
For RandLANet, we don't merge different pointclouds.
While KPConv doesn't have any batch dimension, and different pointclouds in the same batch are concatenated. The nearest neighbors are computed keeping this in consideration.
