### ISSUE TITLE
Hi, is there any recommed annotation tool for 3D data?

### ISSUE THREAD

**Issue by JimXu1989** [isl-org/Open3D-ML#378]
Hi, 
is there any recommed annotation tool for 3D data?

Thanks a lot!!

**Comment by sanskar107** [comment]
@JimXu1989 we don't provide any annotation tool, but you can try some open source repositories like https://github.com/walzimmer/3d-bat

**Comment by JimXu1989** [comment]
> @JimXu1989 we don't provide any annotation tool, but you can try some open source repositories like https://github.com/walzimmer/3d-bat

Thanks a lot, it really helps
