### ISSUE TITLE
Randlanet large run time

### ISSUE THREAD

**Issue by WiNet-Lab-IIT-Hyderabad** [isl-org/Open3D-ML#379]
I am running pretrained Randlanet model on semantickitti data and my own recorded data. In both cases run time is more than 1 sec per frame. If anybody observed the run time please let me know, because the author claims the run time around 0.04sec for 10^5 points.

My system configuration : Intel® Xeon(R) W-2255 CPU @ 3.70GHz × 20 , 64GB RAM, GPU: RTX3090.

**Comment by sanskar107** [comment]
@WiNet-Lab-IIT-Hyderabad We perform iterative inference, where we merge inference results of multiple cropped portions of the pointcloud to support inference on low memory machines. You can try increasing parameter `num_points`.
