### ISSUE TITLE
registry.py get_from_name doc incoherent with actual function

### ISSUE THREAD

**Issue by lc-guy** [isl-org/Open3D-ML#398]
https://github.com/isl-org/Open3D-ML/blob/4c049cee2723df4d1d183329564e5576e39747ea/ml3d/utils/registry.py#L64-L87

**Comment by sanskar107** [comment]
@lc-guy Could you elaborate more on this issue?

**Comment by lc-guy** [comment]
@sanskar107 get_from_name doesn't take two `cfg` and `default_args` dict arguments, as far as I know, but two strings.

**Comment by sanskar107** [comment]
@lc-guy could you create a quick PR to fix this?
Thanks for reporting.
