### ISSUE TITLE
ERROR: Unexpected segmentation fault encountered in worker.

### ISSUE THREAD

**Issue by sai1992c** [isl-org/Open3D-ML#401]
I'm trying to train Randlanet Model from scratch for my custom dataset. My input dim is 8 (3 + 5 features). For now, I just use two trained files to start with. However, I'm getting the following error while initiating `pipeline.run_train()`. The error message is shown below: Kindly help

`model = torch.models.RandLANet(dim_input=8)`
`pipeline = torch.pipelines.SemanticSegmentation(model=model, dataset=dataset, max_epoch=100, device='gpu')`
`pipeline.run_train()`

INFO - 2021-10-10 09:40:05,596 - semantic_segmentation - DEVICE : cpu
INFO - 2021-10-10 09:40:05,597 - semantic_segmentation - Logging in file : ./logs/RandLANet_Custom3D_torch/log_train_2021-10-10_09:40:05.txt
INFO - 2021-10-10 09:40:05,599 - customdataset - Found 2 pointclouds for train
INFO - 2021-10-10 09:40:05,599 - customdataset - Found 0 pointclouds for validation
INFO - 2021-10-10 09:40:05,604 - semantic_segmentation - Initializing from scratch.
INFO - 2021-10-10 09:40:05,606 - semantic_segmentation - Writing summary in train_log/00012_RandLANet_Custom3D_torch.
INFO - 2021-10-10 09:40:05,607 - semantic_segmentation - Started training
INFO - 2021-10-10 09:40:05,608 - semantic_segmentation - === EPOCH 0/100 ===
training:   0%|                                                                                                                                                        | 0/1 [00:00<?, ?it/s]

Shape obtained: (45056, 8)
Shape in configuration: 8

ERROR: Unexpected segmentation fault encountered in worker.
training:   0%|                                                                                                                                                        | 0/1 [00:03<?, ?it/s]
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
~/.conda/envs/semseg/lib/python3.7/site-packages/torch/utils/data/dataloader.py in _try_get_data(self, timeout)
    871         try:
--> 872             data = self._data_queue.get(timeout=timeout)
    873             return (True, data)

~/.conda/envs/semseg/lib/python3.7/multiprocessing/queues.py in get(self, block, timeout)
    103                     timeout = deadline - time.monotonic()
--> 104                     if not self._poll(timeout):
    105                         raise Empty

~/.conda/envs/semseg/lib/python3.7/multiprocessing/connection.py in poll(self, timeout)
    256         self._check_readable()
--> 257         return self._poll(timeout)
    258 

~/.conda/envs/semseg/lib/python3.7/multiprocessing/connection.py in _poll(self, timeout)
    413     def _poll(self, timeout):
--> 414         r = wait([self], timeout)
    415         return bool(r)

~/.conda/envs/semseg/lib/python3.7/multiprocessing/connection.py in wait(object_list, timeout)
    920             while True:
--> 921                 ready = selector.select(timeout)
    922                 if ready:

~/.conda/envs/semseg/lib/python3.7/selectors.py in select(self, timeout)
    414         try:
--> 415             fd_event_list = self._selector.poll(timeout)
    416         except InterruptedError:

~/.conda/envs/semseg/lib/python3.7/site-packages/torch/utils/data/_utils/signal_handling.py in handler(signum, frame)
     65         # Python can still get and update the process status successfully.
---> 66         _error_if_any_worker_fails()
     67         if previous_handler is not None:

RuntimeError: DataLoader worker (pid 3182) is killed by signal: Segmentation fault. 

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_2949/3780324710.py in <module>
----> 1 pipeline.run_train()

~/Open3D-ML/ml3d/torch/pipelines/semantic_segmentation.py in run_train(self)
    387             model.trans_point_sampler = train_sampler.get_point_sampler()
    388 
--> 389             for step, inputs in enumerate(tqdm(train_loader, desc='training')):
    390                 if hasattr(inputs['data'], 'to'):
    391                     inputs['data'].to(device)

~/.conda/envs/semseg/lib/python3.7/site-packages/tqdm/std.py in __iter__(self)
   1178 
   1179         try:
-> 1180             for obj in iterable:
   1181                 yield obj
   1182                 # Update and possibly print the progressbar.

~/.conda/envs/semseg/lib/python3.7/site-packages/torch/utils/data/dataloader.py in __next__(self)
    433         if self._sampler_iter is None:
    434             self._reset()
--> 435         data = self._next_data()
    436         self._num_yielded += 1
    437         if self._dataset_kind == _DatasetKind.Iterable and \

~/.conda/envs/semseg/lib/python3.7/site-packages/torch/utils/data/dataloader.py in _next_data(self)
   1066 
   1067             assert not self._shutdown and self._tasks_outstanding > 0
-> 1068             idx, data = self._get_data()
   1069             self._tasks_outstanding -= 1
   1070             if self._dataset_kind == _DatasetKind.Iterable:

~/.conda/envs/semseg/lib/python3.7/site-packages/torch/utils/data/dataloader.py in _get_data(self)
   1032         else:
   1033             while True:
-> 1034                 success, data = self._try_get_data()
   1035                 if success:
   1036                     return data

~/.conda/envs/semseg/lib/python3.7/site-packages/torch/utils/data/dataloader.py in _try_get_data(self, timeout)
    883             if len(failed_workers) > 0:
    884                 pids_str = ', '.join(str(w.pid) for w in failed_workers)
--> 885                 raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
    886             if isinstance(e, queue.Empty):
    887                 return (False, None)

RuntimeError: DataLoader worker (pid(s) 3182) exited unexpectedly

**Comment by sai1992c** [comment]
tried with num_workers=0, the issue got fixed.

**Comment by preethamam** [comment]
I still have the same issue with `KPCONV`. Including the `num_workers:0` and `pin_memory: False` in `pipeline` of the `.yml` config files resolves the issue.
