### ISSUE TITLE
Wrong legend colors

### ISSUE THREAD

**Issue by h4k1m0u** [isl-org/Open3D-ML#409]
I took the [`(small script)`](https://github.com/isl-org/Open3D-ML#reading-a-dataset) in README.md and replaced only SemanticKITTI as a dataset with S3DIS.
From Open3D visualizer I can easily see that the classes (labels) names in the legend (lower-right corner) are wrong.

For Area3 conference room

![Screenshot](https://user-images.githubusercontent.com/4227512/140391587-272a230f-4d94-4563-8673-0bf2151f87c0.png)

I wrote also a script (inspired by examples/vis_pred.py) where I read labels with `numpy.load()` from predictions and ground truth labels and observed the same problem (playing with LUT didn't solve it either). I suspect it happens when a class is missing in a pointcloud, so classes labels get shifted in the legend.

**Comment by sanskar107** [comment]
Copy of #243
