### ISSUE TITLE
RandLA-Net Licencing Clarification

### ISSUE THREAD

**Issue by ntw-au** [isl-org/Open3D-ML#413]
We would like to use Open3D-ML within our organisation for semantic segmentation of point cloud data, but are concerned about the licencing for the RandLA-Net model.

The original RandLA-Net implementation is licenced under [Creative Commons BY-NC-SA 4.0 International](https://github.com/QingyongHu/RandLA-Net/blob/master/LICENSE), which is a viral licence that also prohibits commercial use.

On the other hand, Open3D-ML is MIT-licenced, which would permit our use case. However, we have noted some locations in the Open3D-ML implementation of RandLA-Net that suggest that the Open3D-ML code is in fact derived from the original RandLA-Net, and therefore should also fall under the CC BY-NC-SA licence.

Examples (baseline commit b8e1eb1abe40e8c9da1eeb317f09e3b973f35da2):
|Function|O3DML TensorFlow|O3DML PyTorch|QingyongHu (Original)|Notes|
|---------|-----------|----------|------------|--------|
|`random_sample`|[Open3D-ML/randlanet.py#L312](https://github.com/isl-org/Open3D-ML/blob/b8e1eb1abe40e8c9da1eeb317f09e3b973f35da2/ml3d/tf/models/randlanet.py#L312)|[Open3D-ML/randlanet.py#L522](https://github.com/isl-org/Open3D-ML/blob/b8e1eb1abe40e8c9da1eeb317f09e3b973f35da2/ml3d/torch/models/randlanet.py#L522)|[RandLA-Net/RandLANet.py#L302](https://github.com/QingyongHu/RandLA-Net/blob/6b5445f5f279d33d2335e85ed39ca8b68cb1c57e/RandLANet.py#L302)|Implementations are very similar, even to the code comments.|
|`nearest_interpolation`|[Open3D-ML/randlanet.py#L334](https://github.com/isl-org/Open3D-ML/blob/b8e1eb1abe40e8c9da1eeb317f09e3b973f35da2/ml3d/tf/models/randlanet.py#L334)|[Open3D-ML/randlanet.py#L550](https://github.com/isl-org/Open3D-ML/blob/b8e1eb1abe40e8c9da1eeb317f09e3b973f35da2/ml3d/torch/models/randlanet.py#L550)|[RandLA-Net/RandLANet.py#L319](https://github.com/QingyongHu/RandLA-Net/blob/6b5445f5f279d33d2335e85ed39ca8b68cb1c57e/RandLANet.py#L319)|As above, with the PyTorch implementation having more differences.|
|`gather_neighbour`|[Open3D-ML/randlanet.py#L334](https://github.com/isl-org/Open3D-ML/blob/b8e1eb1abe40e8c9da1eeb317f09e3b973f35da2/ml3d/tf/models/randlanet.py#L334)|[Open3D-ML/randlanet.py#L361](https://github.com/isl-org/Open3D-ML/blob/b8e1eb1abe40e8c9da1eeb317f09e3b973f35da2/ml3d/torch/models/randlanet.py#L361)|[RandLA-Net/RandLANet.py#334](https://github.com/QingyongHu/RandLA-Net/blob/6b5445f5f279d33d2335e85ed39ca8b68cb1c57e/RandLANet.py#L334)|The PyTorch implementation is significantly different to the original, whereas the TensorFlow implementation is virtually the same.|
|Core model|[Open3D-ML/randlanet.py#518](https://github.com/isl-org/Open3D-ML/blob/b8e1eb1abe40e8c9da1eeb317f09e3b973f35da2/ml3d/tf/models/randlanet.py#L518)|[Open3D-ML/randlanet.py#L209](https://github.com/isl-org/Open3D-ML/blob/b8e1eb1abe40e8c9da1eeb317f09e3b973f35da2/ml3d/torch/models/randlanet.py#L209)|[RandLA-Net/RandLANet.py#L32](https://github.com/QingyongHu/RandLA-Net/blob/6b5445f5f279d33d2335e85ed39ca8b68cb1c57e/RandLANet.py#L32)|Names of data items are the same without variation.|

While there do exist some areas of significant difference, the examples listed above give us pause regarding adoption of Open3D-ML due to RandLA-Net's licencing requirements. As such, we would appreciate some clarification or guidance from the project authors regarding Open3D-ML's licencing status.

**Comment by sanskar107** [comment]
@ntw-au Thanks for reporting this critical issue. We have included RandLANet's CC4 License. Consequently, this prohibits commercial use. We are working on a separate RandLANet's implementation from scratch, which will permit your use case. It should be ready in coming weeks.

**Comment by ntw-au** [comment]
Thank you very much for your response and clarification. We look forward to hearing further news about the new MIT RandLA-Net implementation when it is available.

**Comment by sanskar107** [comment]
@ntw-au The new MIT Licensed RandLA-Net implementation is now available in `dev` branch.

**Comment by ntw-au** [comment]
That's great news @sanskar107, thanks for your work!
