### ISSUE TITLE
windows  Open3D was not built with PyTorch support!

### ISSUE THREAD

**Issue by monkeycc** [isl-org/Open3D-ML#424]
I tried to install several versions
windows  Open3D was not built with PyTorch support!

```
torch                             1.7.1
torchaudio                        0.7.2
torchvision                       0.8.2+cu110
```

```
torch                             1.7.1+cu110
torchaudio                        0.7.2
torchvision                       0.8.2+cu110
```

**Comment by sanskar107** [comment]
Hi @monkeycc 
Unfortunately, windows is not supported right now. You can try using windows subsystem for linux (WSL) to access the functionality on windows 10. We are trying to enable all features on windows, but there is no specific timeline yet.

**Comment by Zador-Pataki** [comment]
Are there any updates to this?
