### ISSUE TITLE
NotImplementedError for Point RCNN

### ISSUE THREAD

**Issue by songming1995** [isl-org/Open3D-ML#426]
Thanks for the great open3d ml package. I met a problem when implementing object prediction with the Point RCNN model. open3d.core.cuda.device_count() returns 0 and raises NotImplementedError. However, torch.cuda.device_count() returns 1, which says the cuda works on my linux 18.04 OS. Hope to get the hints, thanks a lot.

**Comment by sanskar107** [comment]
@songming1995 This happens when Open3D is compiled with a different major version of CUDA than the one installed. Please use CUDA 11.* with latest release of Open3D (>=0.13).
