### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by hbd730** [isl-org/Open3D-ML#430]
I got the following error when installing open3d-ml. 

`Exception: Version mismatch: Open3D needs PyTorch version 1.7.*, but version 1.8.2 is installed!
`
My environment is python3.7 and got opend3d install via pip install open3d, and dependencies installed via requirements-torch-cuda.txt.

Please help!

**Comment by sb1131** [comment]
I had the same error and pulled the requirements for tag 0.13.0 instead of master since my open3d version was 0.13.0 when installing it using pip.

**Comment by hbd730** [comment]
> I had the same error and pulled the requirements for tag 0.13.0 instead of master since my open3d version was 0.13.0 when installing it using pip.

Thanks for the answer, this works for me. :)
