### ISSUE TITLE
Open3d-ml for cuda10.2

### ISSUE THREAD

**Issue by gayathri81** [isl-org/Open3D-ML#440]
Hello, 
Thanks for the code, I am trying to install the setup in python 3.6, cuda 10.2. I see that in the compatibility section CUDA 10.1, 11.*  is mentioned and not cuda 10.2
Is open3d-ml compatible with cuda10.2?
Thanks,
Gayathri.

**Comment by ssheorey** [comment]
Yes, any CUDA version >=10.1 should work.

**Comment by ssheorey** [comment]
Hi @gayathri81 closing this issue. Feel free to reopen if you find any problems.
