### ISSUE TITLE
Can't download ParisLille3D dataset

### ISSUE THREAD

**Issue by mlant** [isl-org/Open3D-ML#442]
Hello,

I notice that the script to download the ParisLille3D dataset doesn't work anymore.
It is required to enter a password on the site to download the dataset : https://npm3d.fr/paris-lille-3d

Thank you,
mlant

**Comment by CamilleMaurice** [comment]
Hello,
The password to download the dataset is on the webpage https://npm3d.fr/paris-lille-3d itself.
Regards,

**Comment by mlant** [comment]
Hello,
Maybe I wasn't clear enough, I mean the script download_parislille3d.sh doesn't work anymore because of this password.
Regards,

**Comment by sanskar107** [comment]
@mlant looks like you have to download the dataset manually by entering password. The `--password` argument for `wget` doesn't work.
