### ISSUE TITLE
Fast inference without building kd-tree

### ISSUE THREAD

**Issue by aliab3d** [isl-org/Open3D-ML#443]
Hi team, thanks for your efforts in putting up a great repository!

My understanding from the RandLaNet paper is that the inference shouldnt be relying on any **pre-processing** stages. With the current implementations in the repo, during training, a **KD-tree** is constructed from each point-cloud and cached for subsequent fetches. Also, during inference, a KD-tree is constructed and a voting scheme is applied to make multiple predictions for each point in the pointcloud and satisfy a confidence threshold.

Since the KD-tree construction is quite time consuming and slows down the inference, can we add an implementation to process the raw pointcloud without KD-tree construction? I understand that the segmentation performance may degrade a bit but it can significantly improve the inference speed, thus a tradeoff between accuracy and processing time for users. This [issue](https://github.com/QingyongHu/RandLA-Net/issues/65) is also raised in the original paper repo.

cheers

**Comment by sanskar107** [comment]
@aliab3d Hey, that's a good suggestion, I tried your approach. Without KD-tree construction, there is a significant drop in performance. Feel free to report if you have different findings.
