### ISSUE TITLE
Semantic3D dataset dimension mismatch error when training from pipeline

### ISSUE THREAD

**Issue by MRTBSKTP** [isl-org/Open3D-ML#445]
Hello, i was experimenting with the library and tried conducting Sem. Seg pipeline with RandLANet using Semantic3D dataset which ı have downloaded on a specific folder. I have managed to instantiniate dataset, model and pipeline objects without problem. But when i call `pipeline.run_train()` method, i get this error; 

 File "/usr/local/lib/python3.7/dist-packages/open3d/_ml3d/tf/models/randlanet.py", line 415, in gen
    1], "Wrong feature dimension, please update dim_input(3 + feature_dimension) in config"

AssertionError: Wrong feature dimension, please update dim_input(3 + feature_dimension) in config

	 [[{{node PyFunc}}]] [Op:IteratorGetNext]

I have checked the both related config file and .txt point cloud files and found a mismatch. In config file dim_input were set 6 initially and i have updated that to 7, regarding both dataset web page and my manual inspection of point cloud files. Each point has 7 features in this dataset i.e. x, y, z, intensity, r, g, b. But pipeline gives the same error ? How do i fix that?

**Comment by sanskar107** [comment]
@MRTBSKTP could you confirm you are using `ml3d/configs/randlanet_semantic3d.yml` as a configuration file?

**Comment by MRTBSKTP** [comment]
Yes, i was using `ml3d/configs/randlanet_semantic3d.yml` but figured problem at somewhere else, while instantiniating the model default config dictionary was overriding that config file so changed it and it worked. Thank you for your time.

**Comment by John-Hiroshi** [comment]
Hi @MRTBSKTP 
I'm facing the same error. Could you possibly show the steps how you solved the error in detail please?
It would be great help.
