### ISSUE TITLE
Hello! How to use crop_point_cloud

### ISSUE THREAD

**Issue by 459737087** [isl-org/Open3D-ML#446]
I've searched docs, it told me to add a json file.
**_o3d.visualization.read_selection_polygon_volume(    "../../test_data/Crop/cropped.json")_**

but  i don't know the file pattern.

**Comment by ssheorey** [comment]
Hi @459737087 the `json` file is pretty simple - you can open it and check the format:

https://github.com/isl-org/Open3D/blob/d9da59ed4d569d06e4a5fc93eea7184aa5ebab40/examples/test_data/Crop/cropped.json#L1-L31

The bounding polygon volume (polygon cylinder) is specified as a polygon with vertices in a plan orthogonal to either the X, Y or Z axes. In addition we need the range along the axes, e.g. Y_min and Y_max.
