### ISSUE TITLE
Import "open3d.visualization.tensorboard_plugin" could not be resolved

### ISSUE THREAD

**Issue by Nireil** [isl-org/Open3D-ML#448]
<img width="468" alt="截屏2021-12-27 上午11 28 53" src="https://user-images.githubusercontent.com/73781932/147431529-c1ccae80-8017-4ab0-9e23-193d2c252da3.png">
I meet this report missing imports error, how to solve it?

**Comment by ssheorey** [comment]
Hi @Nireil do you have `open3d` installed? (`pip install open3d`)
Please tell us enough details to reproduce what you found:
- System, environment (versions of OS, Python, Open3D)
- What commands did you run?
- Complete error message.

**Comment by Nireil** [comment]
> Hi @Nireil do you have `open3d` installed? (`pip install open3d`) Please tell us enough details to reproduce what you found:
> 
> * System, environment (versions of OS, Python, Open3D)
> * What commands did you run?
> * Complete error message.
I have installed open3d, you can see  the "import open3d as o3d" is normal. 
System: Ubuntu 9.3.0-17ubuntu1~20.04
Python: 3.6.13
Open3D: 0.14.1
I didn't run any comands. It is that the tensorboar_plugin is lost, I think.
And the whole script use the "SummaryWriter" rathor than  "summary" .]
Now  I just can't get the visualization of gt and prediction in the TensorBoard after finishing trainning. There is only SCALARS, TEXT, TIME and SERIES .

**Comment by Nireil** [comment]
Do you know how to get that like the https://github.com/isl-org/Open3D-ML/blob/master/docs/tensorboard.md showed?
<img width="744" alt="截屏2022-01-04 下午3 07 32" src="https://user-images.githubusercontent.com/73781932/148022422-e7d598c7-05de-4e5d-b0da-b66d4110398a.png">

**Comment by ssheorey** [comment]
> * I didn't run any comands. It is that the tensorboar_plugin is lost, I think.
>       And the whole script use the "SummaryWriter" rathor than  "summary" .]

That is OK. The "... import summary" adds an extra function to `SummaryWriter` and we can use `SummaryWriter.add_3d()` after that.

>       Now  I just can't get the visualization of gt and prediction in the TensorBoard after finishing trainning. There is only SCALARS, TEXT, TIME and SERIES .

You can test by running the example. `examples/python/gui/tensorboard_pytorch.py`. See the tutorial for details. If something doesn't work please tell us **complete** information about **all** the steps that you ran and the unexpected output / error message.

**Comment by Nireil** [comment]
I ran 'python examples/tensorboard_pytorch.py' ('examples/python/gui/tensorboard_pytorch.py' doesn't exit in this repo), then I got 'examples/demo_data'  and 'demo_logs/pytorch'. I ran 'tensorboard --logdir demo_logs/pytorch/' , after I click into the browser at localhost:6006, there's no result in the column of open3d, then an error in the terminal shows as follows:
![Uploading 截屏2022-01-05 下午4.34.12.png…]()

2022-01-05 16:29:03.470288: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0

NOTE: Using experimental fast data loading logic. To disable, pass
    "--load_fast=false" and report issues on GitHub. More details:
    https://github.com/tensorflow/tensorboard/issues/4784

Serving TensorBoard on localhost; to expose to the network, use a proxy or pass --bind_all
TensorBoard 2.7.0 at http://localhost:6007/ (Press CTRL+C to quit)
/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/werkzeug/filesystem.py:51: BrokenFilesystemWarning: Detected a misconfigured UNIX filesystem: Will use UTF-8 as filesystem encoding instead of 'ascii'
  BrokenFilesystemWarning,
E0105 16:29:19.925945 140283399419648 _internal.py:225] Error on request:
Traceback (most recent call last):
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/werkzeug/serving.py", line 319, in run_wsgi
    execute(self.server.app)
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/werkzeug/serving.py", line 308, in execute
    application_iter = app(environ, start_response)
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/tensorboard/backend/application.py", line 525, in __call__
    return self._app(environ, start_response)
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/tensorboard/backend/application.py", line 566, in wrapper
    return wsgi_app(environ, start_response)
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/tensorboard/backend/security_validator.py", line 77, in __call__
    return self._application(environ, start_response_proxy)
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/tensorboard/backend/path_prefix.py", line 68, in __call__
    return self._application(environ, start_response)
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/tensorboard/backend/experiment_id.py", line 73, in __call__
    return self._application(environ, start_response)
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/tensorboard/backend/empty_path_redirect.py", line 43, in __call__
    return self._application(environ, start_response)
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/tensorboard/backend/application.py", line 589, in wrapper
    return wsgi_app(environ, start_response)
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/tensorboard/backend/application.py", line 548, in _route_request
    return self.exact_routes[clean_path](environ, start_response)
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/werkzeug/wrappers/request.py", line 206, in application
    resp = f(*args[:-2] + (request,))
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/open3d/visualization/tensorboard_plugin/plugin.py", line 799, in _serve_js
    return werkzeug.Response(infile.read(),
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 16677: ordinal not in range(128)

**Comment by ssheorey** [comment]
From `Open3D-ML/docs/tensorboard.md`:
> You can save 3D data as TensorBoard summary when working with either TensorFlow or PyTorch. The 3D data is saved as **'.msgpack'** files (serialized Open3D geometry data) in the **plugins/Open3D** sub-folder with the event files. The examples described below are available in the examples/python/gui/tensorboard_pytorch.py and examples/python/gui/tensorboard_tensorflow.py files **in the Open3D repository.** 

Please note:
- The examples are in the Open3D repo, not Open3D-ML.
- Please ensure that you have the `.msgpack` files in `plugins/Open3D/` inside logdir before running `tensorboard`. Otherwise there is no data for `tensorboard` to display.

**Comment by Nireil** [comment]
> * The examples are in the Open3D repo, not Open3D-ML.
My open3d is installed by pip, and there's no examples in the path. I will try to build from source to get a complete one.

> * Please ensure that you have the `.msgpack` files in `plugins/Open3D/` inside logdir before running `tensorboard`. Otherwise there is no data for `tensorboard` to display.
Actually, I have the the `plugins/Open3D/* .msgpack` files in both `objdet-example` and `semseg-example`  I have got before, but tensorboard doesn't display it.
<img width="786" alt="截屏2022-01-06 上午10 56 15" src="https://user-images.githubusercontent.com/73781932/148321208-f73375e5-0ff3-4d16-9a94-67f6faa3bad7.png">

**Comment by ssheorey** [comment]
Thanks for checking. You will have to clone the Open3D repo to get the other examples. You **don't** need to build the wheel from source. 
What command did you run to create these files?
Please zip the logdir and upload it here so we can take a look.

**Comment by Nireil** [comment]
> Thanks for checking. You will have to clone the Open3D repo to get the other examples. You **don't** need to build the wheel from source. What command did you run to create these files? Please zip the logdir and upload it here so we can take a look.

Sorry for long time delay. 
[demo_logs.zip](https://github.com/isl-org/Open3D-ML/files/7837068/demo_logs.zip)
I ran `Open3D-ML/examples/tensorboard_pytorch.py` to create these files.

**Comment by zituka** [comment]
hi nireil, have you solved this problem?
i have the same question.

**Comment by zituka** [comment]
hi nireil and author, i met the same question.
i have cloned the open3d repo, and mv logdir to open3d repo. 
but tensorboard still shows nothing.

**Comment by Nireil** [comment]
> and mv logdir to open3d repo.
> but tensorboard still shows nothing.

Is it a segmentation fault when you click the open3d in tensorboard page?

**Comment by zituka** [comment]
yes, is it a monitor problem?

**Comment by Nireil** [comment]
It seems [a bug I have reported](https://github.com/isl-org/Open3D/issues/5010). I suppose the error appears in the File "open3d/visualization/async_event_loop.py", line 98 in _thread_main. But I don't know how to fix it either..

**Comment by zituka** [comment]
yes, it seems this docker user has the same problem. [https://github.com/isl-org/Open3D-ML/issues/507](url)
thx for your reply : ) , hope they can fix this bug as soon.

**Comment by zuodexin** [comment]
When I build my docker from `nvidia/cudagl:11.3.0-devel-ubuntu20.04` instead of `nvidia/cuda:11.3.1-cudnn8-devel-ubuntu18.04`, [segfault](https://github.com/isl-org/Open3D-ML/issues/507) was gone but it still can't displays the demo
