### ISSUE TITLE
Unexpected results from SparseConv

### ISSUE THREAD

**Issue by dkurt** [isl-org/Open3D-ML#452]
Open3D version: 0.14.1 (Ubuntu 18.04, Python 3.6.9)

Hi! Here is a reproducer which demonstrates my confusion about SparseConv implementation. The main question is in non-integer input positions. Do we rounding them or flooring? Also, I cannot explain the difference in predictions for last two cases:
```python
import numpy as np
import torch
from open3d.ml.torch.layers import SparseConv

sparse_conv = SparseConv(in_channels=1,
                         filters=1,
                         kernel_size=[3, 3, 3],
                         use_bias=False,
                         normalize=False)
sparse_conv.eval()

sparse_conv.load_state_dict({"kernel": torch.ones([3, 3, 3, 1, 1]),
                             "offset": sparse_conv.state_dict()["offset"]})

features = torch.ones([2, 1])

# Points are in WHD order
with torch.no_grad():
    inp_pos = torch.tensor(np.array([[1, 2, 0], [0, 1, 0]], dtype=np.float32))
    out = sparse_conv(features, inp_pos, inp_pos, voxel_size=1.0)
    print(out)

    inp_pos = torch.tensor(np.array([[1, 2.53, 0], [0, 1, 0]], dtype=np.float32))
    out = sparse_conv(features, inp_pos, inp_pos, voxel_size=1.0)
    print(out)

    inp_pos = torch.tensor(np.array([[1, 2.531, 0], [0, 1, 0]], dtype=np.float32))
    out = sparse_conv(features, inp_pos, inp_pos, voxel_size=1.0)
    print(out)
```

output:
```
tensor([[2.],
        [2.]])
tensor([[2.],
        [2.]])
tensor([[1.],
        [1.]])
```

**Comment by dkurt** [comment]
Prepared another simplified example which probably can be more helpful. Can you please guide me what's wrong in my calculations?
```python
import numpy as np
import torch
from open3d.ml.torch.layers import SparseConv

sparse_conv = SparseConv(in_channels=1,
                         filters=1,
                         kernel_size=[3, 3, 3],
                         use_bias=False,
                         normalize=False)
sparse_conv.eval()

kernel = torch.ones([3, 3, 3, 1, 1])  # DHWIO

i = 1
for d in range(3):
    for h in range(3):
        for w in range(3):
            kernel[d, h, w, 0, 0] = i
            i += 1

sparse_conv.load_state_dict({"kernel": kernel,
                             "offset": sparse_conv.state_dict()["offset"]})

features = torch.ones([2, 1])
inp_pos = torch.tensor([1.46057, 3.3381, 0.504631,
                        1.00087, 2.48036, 1.01154]).reshape(-1, 3)

out = sparse_conv(features, inp_pos, inp_pos, voxel_size=1.0)
print(out)
```
output: `[34, 22]`

Input is a full ones tensor. Kernel has the following structure:
```
depth 0
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

depth 1
tensor([[10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]])

depth 2
tensor([[19., 20., 21.],
        [22., 23., 24.],
        [25., 26., 27.]])
```



Both points are inside the kernel radius. Question is which weights are used? In example, for the 0th point we accumulate `14*1` as a center of kernel but why second operand is `20*1` which is (1, 0, 2). The difference between points is `[-0.4597, -0.85774, 0.56909]`.

**Comment by benjaminum** [comment]
Hi @dkurt the SparseConv layer is implemented as a special case of this operation http://www.open3d.org/docs/latest/python_api/open3d.ml.torch.ops.continuous_conv.html#open3d.ml.torch.ops.continuous_conv .
The 0.51 is used to avoid edge cases when computing the neighbors.
The layer assumes that all voxel centers lie on a regular grid with grid spacing `voxel_size`. The origin of the grid is not shared. For each output point the filter center coincides with that points positions. You could have a set of points with positions [(0,0,0), (0,0,1), (0,0,2),...] and another set of points [(0,0,100.8), (0,0,101.8), (0,0,102.8)] which is shifted by 0.8 and for both sets you would get the same result given that they have the same features.

Your examples break the regular grid assumption which gives the output you describe.

**Comment by dkurt** [comment]
Hi, @benjaminum! Seems like I understood it. I though that grid should be equal to radius divided by kernel size (1.02 but it's 1.00). So in my example, `[-0.4597, -0.85774, 0.506909]` is mapped to `[1, 0, 2]` rather than `[1, 0, 1]`

**Comment by benjaminum** [comment]
Yes, `voxel_size` defines the grid spacing. The radius is used internally for determining the neighbors. Let me know if you more help with the internals.
