### ISSUE TITLE
KeyError :'' while loading the Toronto3d and Paris_Lille3d Data

### ISSUE THREAD

**Issue by muditrastogi** [isl-org/Open3D-ML#453]
I was trying inferencing on Toronto3d and Paris_Lille3d Data. While loading the test data  i am getting 

`Traceback (most recent call last):`
 `File "run_inference.py", line 31, in <module>`
 `   data = test_split.get_data(0)
`
`  File "/home/aiml/user/Open3D-ML/ml3d/datasets/parislille3d.py", line 198, in get_data
` 
`   points = pc['points'].numpy().astype(np.float32)
`
`KeyError: ''`

Unable to load data.

**Comment by muditrastogi** [comment]
Now it is working after I tried again after re-activating the virtualenv. I don't know the reason but now i am getting 
```
Accuracy [nan,nan,nan]
iou [nan,nan,nan]
```
Also i need to know how to visualize the output produced.

**Comment by sanskar107** [comment]
@muditrastogi  Which model are you using?
Also, test data of ParisLille3D doesn't contain ground truth labels, so `nan` values are expected.

**Comment by muditrastogi** [comment]
RandlaNet

**Comment by sanskar107** [comment]
We have a new MIT licensed version of RandLANet (PR #454) which will fix this problem. It produces even better results than we had before.
