### ISSUE TITLE
How to change input tensor? Which file can modify it?

### ISSUE THREAD

**Issue by ydl45** [isl-org/Open3D-ML#457]
When i train my own datasets, it tips :
RuntimeError:weight tensor should be defined either for all 19 classes or no classes but got weight tensor of shape:[1 x 8] at /pytorch/aten/src/THCUNN/generic/ClassNLLCriterion.cu:44

i modified the semantic3d.py and used it.
Who can tell me how to do it?
Thank you.

**Comment by ssheorey** [comment]
Hi @ydl45 please let us know:
- Your updated config file.
- Info about your custom dataset - number of classes, training set size, etc.
- Which model are you training?

**Comment by sanskar107** [comment]
@ydl45 It looks like you didn't change the default `class_weights` parameter from semantic3d dataset. It has 8 classes while your dataset has 19. Either leave it empty, or pass all 19 ones.
