### ISSUE TITLE
RandLA-Net (torch) pretrained weights missing

### ISSUE THREAD

**Issue by joh4n** [isl-org/Open3D-ML#458]
When I try to fetch any of the pretrained weights for RandLA-Net (torch) from https://github.com/isl-org/Open3D-ML/blob/master/model_zoo.md  

ex. https://storage.googleapis.com/open3d-releases/model-zoo/randlanet_semantickitti_202009090354utc.pth

it results in accessDenied

```
<Error>
<Code>AccessDenied</Code>
<Message>Access denied.</Message>
<Details>Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object.</Details>
</Error>
```

**Comment by sanskar107** [comment]
We have updated RandLANet with a new implementation from scratch (PR #454), and consequently the weights links have been updated. The PR is yet to be merged, please use the branch `sanskar/randlanet` for now.

**Comment by joh4n** [comment]
thank you

**Comment by ssheorey** [comment]
New RandLANet PR is merged. Weights are available. (See `readme` in the `dev` branch).
