### ISSUE TITLE
Inference using my own point cloud on Scannet dataset using SparseConv

### ISSUE THREAD

**Issue by Wavelet303** [isl-org/Open3D-ML#463]
Hello, first of all congratulations for your incredible work. Currently I have accurately reconstructed indoor scenes using Bundlefusion, obtaining similar results to Scannet's 3D dataset models. In turn, the points clouds are aligned on the axes just like Scannet. How can I make the inference easily on the model using my own point cloud? That is, in what format should you load/save the point cloud? Is it necessary to make a transformation of this before?
Thanks for your time.

**Comment by sanskar107** [comment]
Hi @Wavelet303,
You can follow these steps:
1) Load the config file `ml3d/configs/sparseconvunet_scannet.yml`. (Refer https://github.com/isl-org/Open3D-ML#loading-a-config-file).
2) Create model(SparseConvUnet) and pipeline (SemanticSegmentation) object and pass the config file parameters.
3) Run `pipeline.run_inference(data)` to get your inference. Here `data` is a dict with keys {'point', 'feat', 'label'}.

**Comment by Wavelet303** [comment]
Thank you for your prompt and detailed response ;) .  I will try to make the inference following your valuable advice
