### ISSUE TITLE
Invalid dataset Path

### ISSUE THREAD

**Issue by girmzewdie** [isl-org/Open3D-ML#466]
I wanted to use the semantic segmentation(S3DIS) pipeline of the open3d-ML module for indoor semantic segmentation. I have downloaded the repo to my local PC and installed all the required packages on my ubuntu server and tested that the open3d-ML module is working. Then, I downloaded and extracted the S3DIS dataset and stored it in the directory  (... /Open3D-ML/datasets/S3DIS/)--the screenshot is attached.
I followed the instructions to read the dataset and got the following error. I couldn't figure out where the problem is.

I would appreciate your help in advance.

Traceback (most recent call last):
  File "/home/jovyan/desktop/codes/Open3D-ML/try3.py", line 4, in <module>
    dataset = ml3d.datasets.S3DIS(dataset_path='/desktop/codes/Open3D-ML/datasets/S3DIS/Stanford3dDataset_v1.2_Aligned_Version/')
  File "/home/jovyan/anaconda3/envs/open3dpointnet2/lib/python3.9/site-packages/open3d/_ml3d/datasets/s3dis.py", line 77, in __init__
    assert isdir(dataset_path), f"Invalid dataset path {dataset_path}"
AssertionError: Invalid dataset path /desktop/codes/Open3D-ML/datasets/S3DIS/Stanford3dDataset_v1.2_Aligned_Version/
![Capture2](https://user-images.githubusercontent.com/85134979/150968463-7fedeaa7-81fc-4cb3-a960-a674462b3dc6.PNG)

**Comment by ssheorey** [comment]
@girmzewdie your dataset path looks incorrect. It should probably be:
`"/home/jovyan/desktop/codes/Open3D-ML/datasets/S3DIS/Stanford3dDataset_v1.2_Aligned_Version/"`
