### ISSUE TITLE
randlanet_url is not accesible

### ISSUE THREAD

**Issue by kimdn** [isl-org/Open3D-ML#469]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D-ML/issues).
- [X] I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

I tried to follow https://github.com/isl-org/Open3D-ML/blob/master/docs/howtos.md

However, 
randlanet_url = "https://storage.googleapis.com/open3d-releases/model-zoo/randlanet_semantickitti_202009090354utc.pth"
seems not accesible.

### Steps to reproduce the bug

First, at colab

```
randlanet_url = "https://storage.googleapis.com/open3d-releases/model-zoo/randlanet_semantickitti_202009090354utc.pth"

ckpt_path = "./logs/vis_weights_{}.pth".format('RandLANet')
if not exists(ckpt_path):
    cmd = "wget {} -O {}".format(randlanet_url, ckpt_path)
    os.system(cmd)
print (f"ckpt_path:{ckpt_path}")
```

Second, at macOS commandline
`WE39390:~ kimd999$ wget https://storage.googleapis.com/open3d-releases/model-zoo/randlanet_semantickitti_202009090354utc.pth
`

### Error message
First, at colab
downloaded vis_weights_RandLANet.pth is empty.

Second, from macOS commandline
```
--2022-02-05 17:45:04--  https://storage.googleapis.com/open3d-releases/model-zoo/randlanet_semantickitti_202009090354utc.pth
Resolving storage.googleapis.com (storage.googleapis.com)... 142.250.217.80, 172.217.14.208, 142.250.69.208, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.250.217.80|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2022-02-05 17:45:05 ERROR 403: Forbidden.
```

### Open3D, Python and System information

```markdown
- Operating system: google colab pro+
- Python version: Python 3.7.12
- Open3D version: 0.14.1
- Is this remote workstation?: yes (google cloud)
- How did you install Open3D?: !pip install open3d
```

**Comment by sanskar107** [comment]
@kimdn We have updated the RandLANet model and its weights. Please use the `dev` branch for the new links. It will be merged to master in coming week with the next release.
