### ISSUE TITLE
Problem in toronto3d dataset

### ISSUE THREAD

**Issue by INF800** [isl-org/Open3D-ML#471]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D-ML/issues).
- [X] I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Hi, the labels are not falling on point clouds correctly in toronto3d dataset

![image](https://user-images.githubusercontent.com/45640029/152959261-19bb3166-9065-4f00-82ae-6e2989911c2b.png)

**Comment by INF800** [comment]
Reproduced in this colab https://colab.research.google.com/drive/1Y9KbAJ484Kufuc_qDuCP8fBV91ec95gP?usp=sharing

**Comment by INF800** [comment]
@sanskar107 any leads?

**Comment by INF800** [comment]
Interestingly when I use the open3d visualizer, there are no issues. And I am using the same data structure of points, feats and labels

![Screenshot from 2022-02-11 18-41-23](https://user-images.githubusercontent.com/45640029/153597366-2a51f6bb-0f96-447d-bf40-462383952fb1.png)

**Comment by Pyarelal45** [comment]
when i am running the Randla Net on toronto3D, I am getting the error 
![image](https://user-images.githubusercontent.com/75324891/159252710-1142d14a-70c5-4f3c-93f6-8e7637e16ac4.png)

Any idea why it is happening?

**Comment by INF800** [comment]
The issue is related to point cloud density. Everything is working perfectly fine.
