### ISSUE TITLE
Scale of class weights

### ISSUE THREAD

**Issue by INF800** [isl-org/Open3D-ML#475]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D-ML/issues).
- [X] I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Hi, I am using this config file currently for training my custom model.

https://github.com/isl-org/Open3D-ML/blob/8ddb67206e4fef55b39eea691ff00d49cef18be5/ml3d/configs/randlanet_toronto3d.yml#L5

But I do not understand the scale of individual class weights. How to interpret them?

Usually, don't we assign class wights such that sum of all the weights is zero?

**Comment by sanskar107** [comment]
@INF800 `class_weights` represents label count for each individual class. It is then normalised by sum of all counts in the preprocessing stage.

**Comment by INF800** [comment]
Can you please explain with an example. It is still unclear to me.


This is what I am thinking - to keep things simple let's use 3 classes (including background). Assuming at preprocessing stage we have `200k` points. And label counts are -

- `120k`: unlabelled
- `50k`: class 1
- `30k`: class 2

So now, how will be the class weights 1. Ignoring the background class 2. Including the background class.
