### ISSUE TITLE
ml3d.vis.Visualizer() not work with Colab 

### ISSUE THREAD

**Issue by RamizMohareb** [isl-org/Open3D-ML#488]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D-ML/issues).
- [X] I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Helo
I tray to Run the below code at google Colab but the code take long time at "ml3d.vis.Visualizer()" and i expect the viewer Open3d open but it does not open

![image](https://user-images.githubusercontent.com/88134663/157237941-df743ec0-56ee-4b48-99f5-9f8caf764090.png)

`!pip install open3d
!git clone https://github.com/intel-isl/Open3D-ML.git
!pip install -r /content/Open3D-ML/requirements-torch-cuda.txt

import numpy as np
import open3d.ml.torch as ml3d

data = [ {
    'name': 'my_point_cloud',
    'points': np.random.rand(100,3).astype(np.float32),
    'point_attr1': np.random.rand(100).astype(np.float32),
    } ]

vis = ml3d.vis.Visualizer()
vis.visualize(data)

`
Note:
-My operating system is windows 10
-I used Colab because the 'import open3d.ml.torch as ml3d' not work with windows when i used "Anaconda" and "jupyter notebook"

also i tray to run the below smal code from Open3d to view pointcloud at Colab and Jupter. It is work at Jupter and the view work but at the Colab give me error
![image](https://user-images.githubusercontent.com/88134663/157243592-b5c63d1d-c02e-43f8-b168-7534c6d3e5e2.png)

![image](https://user-images.githubusercontent.com/88134663/157243789-e141313f-cf9c-4a69-a15a-04ea2acf1366.png)

**Comment by naruarjun** [comment]
Hello,
Please have a look at this issue. https://github.com/isl-org/Open3D/issues/1026. It suggests some workarounds that may be useful for you. But since Colab doesn't allow for 3rd party plugins, Open3D visualization does not run correctly.
