### ISSUE TITLE
How to do 6-fold cross-validation and train on S3DIS dataset ?

### ISSUE THREAD

**Issue by MrAirplaneLu** [isl-org/Open3D-ML#516]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D-ML/issues).
- [X] I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

How can I do 6-fold cross-validation on the S3DIS dataset, I am using Stanford3dDataset_v1.2_Aligned_Version
Should I train test_area_idx from 1 to 6 and then validate?
what should I do? Many thanks!

**Comment by yeminglang** [comment]
Same problem! By the way,may I ask your result on Stanford3dDataset_v1.2_Aligned_Version? I'll be glad if you can get in touch with me by qq:1253174115 to have farther discussion!

**Comment by sanskar107** [comment]
Yes, you have to manually change the `test_area_idx` to get the 6 fold cross validation.

**Comment by MrAirplaneLu** [comment]
When I train and test model on S3DIS Area 5,only got about 57% miou
I don't know why?
what is the problems? Many thanks!
Environment:torch1.8.2 cuda11.1 open3d0.10.0
![image](https://user-images.githubusercontent.com/45754132/163926582-65f0286f-d024-4f56-996e-4678b8b0e412.png)
![image](https://user-images.githubusercontent.com/45754132/163926594-bafe4f4e-9172-4f67-89d5-3f15fdfda4e8.png)
