### ISSUE TITLE
S3DIS version and class weights setting on S3DIS

### ISSUE THREAD

**Issue by yeminglang** [isl-org/Open3D-ML#519]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D-ML/issues).
- [X] I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Please allow me to ask two questions:
1. Which version of the S3DIS dataset should be used? Stanford3dDataset_v1.2 or Stanford3dDataset_v1.2_Aligned_Version?
2. How to set class weights on area 5 of Stanford3dDataset_v1.2_Aligned_Version (and on other areas)？

**Comment by sanskar107** [comment]
1. Stanford3dDataset_v1.2_Aligned_Version
2. You should calculate the number of instances of each class across your training data. So if your test area is 5, then calculate counts for all other areas.
