### ISSUE TITLE
Download pretrained model of RandLA-net failed 

### ISSUE THREAD

**Issue by samuel1208** [isl-org/Open3D-ML#522]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D-ML/issues).
- [X] I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

when I download the RandLA pretrained model in model zoo , I get the following error 
`Error`
`Code>AccessDenied</Code>`
`<Message>Access denied.</Message> `
`<Details>Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object.</Details>`
`</Error>`

**Comment by lwndlnd** [comment]
I think the updated weigths are here: https://github.com/isl-org/Open3D-ML#tasks-and-algorithms (see also #469)

**Comment by samuel1208** [comment]
> I think the updated weigths are here: https://github.com/isl-org/Open3D-ML#tasks-and-algorithms (see also #469)

Great，I can download from this link
