### ISSUE TITLE
What should the Semantic Kitti Dataset folder structure look like?

### ISSUE THREAD

**Issue by DeepDuke** [isl-org/Open3D-ML#577]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D-ML/issues).
- [X] I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Hi, I want to read Semantic Kitti Dataset use
```python
dataset = ml3d.datasets.SemanticKITTI(dataset_path='/path/to/SemanticKITTI/')
```

and I also download Semantic Kitti Dataset according to the link from http://semantic-kitti.org/dataset.html#download. 
However,  the scan data ,  labels and poses are downloaded from different links. 

I don't know what shoud the  dataset folder structure  look like if I want to use this api to read  Semantic Kitti dataset?

**Comment by vipul-maheshwari** [comment]
The SemanticKITTI dataset is organized in a specific directory structure, which is necessary for the dataset class to correctly read the data. The exact structure depends on which version of the dataset you downloaded, but a typical structure might look like this:  ![Screenshot 2023-01-20 184019](https://user-images.githubusercontent.com/86592569/213702664-74eaac8b-d248-4089-a216-8877260ba19b.png)  

Where "sequences" folder contains subfolders for each sequence of the dataset, each sequence folder contains "velodyne" folder which contains the point cloud data in binary format, "labels" folder which contains the semantic labels of each point in the point cloud and "poses" folder contains the poses of each scan in the sequence. Each sequence folder is named as a number starting from 00 to 21.

I guess that the version of the dataset you downloaded may have a slightly different structure. You should check the documentation provided with the dataset for the specific directory structure you need to use. Also, make sure that the dataset path passed in the dataset class is the path to the root directory of the dataset and not the path to any specific sequence or folder.  It is better to hold the dataset reference in accordance to the directory hierarchy!!

**Comment by DeepDuke** [comment]
TKS!
