### ISSUE TITLE
Cannot execute "import open3d.ml.torch as ml3d" on Ubuntu18

### ISSUE THREAD

**Issue by DonghunP** [isl-org/Open3D-ML#588]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D-ML/issues).
- [X] I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

#### I first cloned Open3D-ML by:
```
git clone https://github.com/isl-org/Open3D-ML.git
cd Open3D-ML
```

#### Then, I set OPEN3D_ML_ROOT with:
```
python -c "import open3d.ml.torch as ml3d"
```

### Error message

```shell
>> python -c "import open3d.ml.torch as ml3d"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/anaconda3/envs/open3d/lib/python3.8/site-packages/open3d/ml/torch/__init__.py", line 38, in <module>
    match_torch_ver = '.'.join(_o3d_torch_version.release[:2] + ('*',))
TypeError: sequence item 0: expected str instance, int found
```

### Open3D, Python and System information

```markdown
- Operating system: (Ubuntu 18.04)
- Python version: (Python 3.8)
- Open3D version: (0.16.0)
- System type: (arm64)
- Is this remote workstation?: yes
- How did you install Open3D?: (pip)
- Compiler version (if built from source): built from source --> No
```

**Comment by sillsill777** [comment]
Same here. I searched through `/open3d/ml/torch/__init__.py", line 38` and find out 

`match_torch_ver = '.'.join(_o3d_torch_version.release[:2] + ('*',))` should be somewhat fixed like below

`match_torch_ver = '.'.join([str(i_) for i_ in _o3d_torch_version.release[:2] + ('*',)])`

Anyway after fixing, it still outputs error like below 
`Exception: Version mismatch: Open3D needs PyTorch version 1.12.*, but version 1.13.1+cu116 is installed!`

**Comment by sillsill777** [comment]
I've managed to solve the issue.

Go to `Open3D-ML/requirements-torch-cuda.txt`
change
`torch==1.13.1+cu116` to -> `torch==1.12.1+cu116`
change
`torchvision==0.14.1+cu116` to -> `torchvision==0.13.1+cu116`

**Comment by ssheorey** [comment]
You are using different versions of Open3D (v0.16) and Open3D-ML (master). You can either use the same version (v0.16 or v0.17 or master for both) to fix this. Open3D master branch wheels can be installed from here:

`pip install open3d --trusted-host www.open3d.org -f http://www.open3d.org/docs/latest/getting_started.html`

**Comment by shawnding** [comment]
> 

Hi, I cannot see how changing a local file would help with `pip install`. I tried to modify `Open3D-ML/requirements-torch-cuda.txt` and then `pip install open3d` but got the same exception message.

My environment: 
- Python 3.8
- PyTorch 1.10.1
- CUDA 11.3

I might have missed something important. How did you solve this issue? Thanks!
