### ISSUE TITLE
How do I add a custom colormap to o3dml.vis.Visualizer programmatically?

### ISSUE THREAD

**Issue by YishGene** [isl-org/Open3D-ML#625]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D-ML/issues).
- [X] I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

I would like to visualize one of the features in a custom Dataset using a custom Colormap, including max and min values that are respectively smaller and larger than the data in the feature. 

I understand more or less how to edit the colormap using the ColormapEdit widget, but how do I use a default without changing code in the package?

**Comment by ssheorey** [comment]
You can clone Open3D-ML and modify the colormap here:
https://github.com/isl-org/Open3D-ML/blob/main/ml3d/vis/colormap.py

Set the Open3D_ML_ROOT env var to point to the local OPen3D-ML folder.

The visualizer will then use your modified colormap. If it's a popular / well regarded colormap that others will find useful, please consider making a PR for the additional colormap.
