### ISSUE TITLE
How to visualize network predictions for semantickitti 

### ISSUE THREAD

**Issue by antonis-nt** [isl-org/Open3D-ML#631]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D-ML/issues).
- [X] I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `main` branch).

### My Question

I have used the example in How tos section, Visualize network predictions but i'm having a hard time understanding how to correct use the pcs = get_data() function for semantickitti. In the example it uses get_custom_data but it says that you can use existing get_data() methods in ml3d/datasets. In this case how can this be modified?

    data_path = '/path/to/SemanticKITTI/'  
    pc_names = ["000700", "000750"]
    pcs = get_data()

After that, how to visualize point clouds with their corresponding predictions using the given example?

    vis_d = {
        "name": name,
        "points": pts, # n x 3
        "labels": label, # n
        "pred": pred_label, # n
    }

**Comment by ssheorey** [comment]
Please see the documentation:
https://github.com/isl-org/Open3D-ML/blob/main/docs/howtos.md#visualize-network-predictions
During training, you can use tensorboard:
https://github.com/isl-org/Open3D-ML/blob/main/docs/tensorboard.md
