### ISSUE TITLE
Summarize the issue and your environments (e.g., "Cannot import ml3d on Ubuntu 20.04 with CUDA")

### ISSUE THREAD

**Issue by Harish1120** [isl-org/Open3D-ML#635]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D-ML/issues).
- [X] I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `main` branch).

#### I first cloned Open3D-ML by:
```
git clone https://github.com/isl-org/Open3D-ML.git
cd Open3D-ML
```

pip installed requirements-torch.txt
```


### Error message

```shell
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/lustre03/project/6070689/harishs/open3d/lib/python3.9/site-packages/open3d/ml/torch/__init__.py", line 39, in <module>
    raise Exception('Version mismatch: Open3D needs PyTorch version {}, but '
Exception: Version mismatch: Open3D needs PyTorch version 1.8.*, but version 2.0.1+cpu is installed!
```

### Open3D, Python and System information

```markdown
- Operating system: HPC (Compute canada, Linux) 
- Python version: (e.g. Python 3.9)
- Open3D version: `0.15.2`
- Is this remote workstation?: yes 
- How did you install Open3D?: pip
```

**Comment by ssheorey** [comment]
Please update to the latest Open3D version 0.18 for Pytorch 2.0 support.
